<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use App\Models\Lesson;

class ExerciseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $allExercises = [];
        $allTopicsByGrade = $this->getTopicsAndQuestions();

        foreach ($allTopicsByGrade as $grade_id => $topics) {
            // Lấy các ID bài học có sẵn cho khối lớp hiện tại để liên kết bài tập.
            $lessonIds = Lesson::where('grade_id', $grade_id)->pluck('id');

            // Nếu không có bài học nào cho khối này, hãy bỏ qua.
            if ($lessonIds->isEmpty()) {
                continue;
            }

            foreach ($topics as $topicData) {
                // Chuyển đổi câu hỏi sang định dạng mới (15 câu, đáp án là chỉ số)
                $transformedQuestions = $this->transformQuestions($topicData['questions']);

                $allExercises[] = [
                    'lesson_id' => $lessonIds->random(), // Gán ngẫu nhiên cho một bài học trong cùng khối lớp
                    'title' => "Bài tập - {$topicData['topic']}",
                    'type' => 'toan', // Theo ví dụ của bạn
                    'description' => "Luyện tập về chủ đề {$topicData['topic']}",
                    'questions' => json_encode($transformedQuestions),
                    'created_at' => now(),
                    'updated_at' => now(),
                ];
            }
        }

        // Xóa các bài tập cũ để tránh trùng lặp nếu chạy lại seeder
        DB::table('exercises')->delete();
        
        // Chèn tất cả các bài tập cùng một lúc
        DB::table('exercises')->insert($allExercises);
    }

    /**
     * Chuyển đổi định dạng câu hỏi và chỉ lấy 15 câu.
     */
    private function transformQuestions(array $questions): array
    {
        $transformed = [];
        // Lấy 15 câu hỏi đầu tiên
        $slicedQuestions = array_slice($questions, 0, 15);

        foreach ($slicedQuestions as $q) {
            $correctIndex = array_search($q['answer'], $q['options']);
            
            // Đảm bảo tìm thấy đáp án, nếu không thì mặc định là 0
            if ($correctIndex === false) {
                $correctIndex = 0;
            }

            $transformed[] = [
                'question' => $q['q'],
                'options' => $q['options'],
                'correctAnswer' => $correctIndex,
            ];
        }
        return $transformed;
    }

    /**
     * Cung cấp danh sách các chủ đề và 20 câu hỏi cho mỗi chủ đề, theo từng khối lớp.
     */
    private function getTopicsAndQuestions(): array
    {
        return [
            // ========== LỚP 1 ==========
            1 => [
                ['topic' => 'Làm quen với một số hình', 'questions' => [
                    ['q' => 'Quả bóng có dạng hình gì?', 'options' => ['Hình vuông', 'Hình tròn', 'Hình tam giác', 'Hình chữ nhật'], 'answer' => 'Hình tròn'],
                    ['q' => 'Quyển sách giáo khoa có dạng hình gì?', 'options' => ['Hình tròn', 'Hình chữ nhật', 'Hình vuông', 'Hình tam giác'], 'answer' => 'Hình chữ nhật'],
                    ['q' => 'Hình vuông có mấy cạnh?', 'options' => ['3 cạnh', '4 cạnh', '5 cạnh', '2 cạnh'], 'answer' => '4 cạnh'],
                    ['q' => 'Các cạnh của hình vuông như thế nào với nhau?', 'options' => ['Bằng nhau', 'Không bằng nhau', 'Chỉ có 2 cạnh bằng nhau', 'Cạnh dài cạnh ngắn'], 'answer' => 'Bằng nhau'],
                    ['q' => 'Hình tam giác có mấy góc?', 'options' => ['2 góc', '3 góc', '4 góc', '1 góc'], 'answer' => '3 góc'],
                    ['q' => 'Mặt đồng hồ treo tường thường có dạng hình gì?', 'options' => ['Hình tròn', 'Hình vuông', 'Hình tam giác', 'Hình thoi'], 'answer' => 'Hình tròn'],
                    ['q' => 'Bánh xe đạp có dạng hình gì?', 'options' => ['Hình chữ nhật', 'Hình tròn', 'Hình tam giác', 'Hình vuông'], 'answer' => 'Hình tròn'],
                    ['q' => 'Lá cờ Tổ quốc Việt Nam có dạng hình gì?', 'options' => ['Hình vuông', 'Hình tam giác', 'Hình chữ nhật', 'Hình tròn'], 'answer' => 'Hình chữ nhật'],
                    ['q' => 'Hình nào không có góc?', 'options' => ['Hình vuông', 'Hình tròn', 'Hình tam giác', 'Hình chữ nhật'], 'answer' => 'Hình tròn'],
                    ['q' => 'Viên gạch hoa thường có dạng hình gì?', 'options' => ['Hình tròn', 'Hình vuông', 'Hình tam giác', 'Hình elip'], 'answer' => 'Hình vuông'],
                    ['q' => 'Cái đĩa có dạng hình gì?', 'options' => ['Hình tròn', 'Hình vuông', 'Hình chữ nhật', 'Hình tam giác'], 'answer' => 'Hình tròn'],
                    ['q' => 'Khung cửa sổ có dạng hình gì?', 'options' => ['Hình tròn', 'Hình tam giác', 'Hình chữ nhật', 'Hình thang'], 'answer' => 'Hình chữ nhật'],
                    ['q' => 'Biển báo giao thông cấm đi ngược chiều có dạng hình gì?', 'options' => ['Hình tròn', 'Hình vuông', 'Hình tam giác', 'Hình chữ nhật'], 'answer' => 'Hình tròn'],
                    ['q' => 'Hình chữ nhật có mấy cặp cạnh đối diện bằng nhau?', 'options' => ['1 cặp', '2 cặp', '3 cặp', '4 cặp'], 'answer' => '2 cặp'],
                    ['q' => 'Mái nhà thường có dạng hình gì?', 'options' => ['Hình tròn', 'Hình tam giác', 'Hình vuông', 'Hình chữ nhật'], 'answer' => 'Hình tam giác'],
                ]],
                ['topic' => 'Các số đến 10', 'questions' => [
                    ['q' => 'Số liền sau của số 8 là số nào?', 'options' => ['7', '9', '10', '8'], 'answer' => '9'],
                    ['q' => 'Trong các số 2, 5, 9, 7, số nào lớn nhất?', 'options' => ['5', '7', '9', '2'], 'answer' => '9'],
                    ['q' => 'Số liền trước của số 7 là số nào?', 'options' => ['6', '8', '5', '7'], 'answer' => '6'],
                    ['q' => 'Trong các số 1, 10, 3, 8, số nào bé nhất?', 'options' => ['1', '10', '3', '8'], 'answer' => '1'],
                    ['q' => 'Số đứng giữa số 4 và số 6 là số nào?', 'options' => ['3', '5', '7', '4'], 'answer' => '5'],
                    ['q' => 'Đếm ngược từ 5, số tiếp theo là?', 'options' => ['6', '4', '3', '5'], 'answer' => '4'],
                    ['q' => 'Có bao nhiêu số tự nhiên nhỏ hơn 5?', 'options' => ['3', '4', '5', '6'], 'answer' => '5'],
                    ['q' => 'Số 9 gồm 5 và mấy?', 'options' => ['3', '4', '5', '2'], 'answer' => '4'],
                    ['q' => 'Gộp 3 và 6 được mấy?', 'options' => ['8', '9', '10', '7'], 'answer' => '9'],
                    ['q' => 'Số chẵn lớn nhất nhỏ hơn 10 là?', 'options' => ['10', '9', '8', '6'], 'answer' => '8'],
                    ['q' => 'Số lẻ bé nhất lớn hơn 1 là?', 'options' => ['1', '2', '3', '5'], 'answer' => '3'],
                    ['q' => 'Có 7 bông hoa, thêm 2 bông hoa nữa. Tổng cộng có mấy bông hoa?', 'options' => ['8', '9', '10', '7'], 'answer' => '9'],
                    ['q' => 'Số nào vừa lớn hơn 3 vừa bé hơn 5?', 'options' => ['2', '4', '6', '3'], 'answer' => '4'],
                    ['q' => 'Số "chín" được viết là?', 'options' => ['6', '8', '9', '7'], 'answer' => '9'],
                    ['q' => 'Số 5 đọc là gì?', 'options' => ['Năm', 'Lăm', 'Nâm', 'Lên'], 'answer' => 'Năm'],
                ]],
                ['topic' => 'So sánh các số: bằng, lớn hơn, bé hơn', 'questions' => [
                    ['q' => 'Số 9 ... số 6?', 'options' => ['Lớn hơn', 'Bé hơn', 'Bằng', 'Không so sánh được'], 'answer' => 'Lớn hơn'],
                    ['q' => 'Số 5 ... số 5?', 'options' => ['Lớn hơn', 'Bé hơn', 'Bằng', 'Không so sánh được'], 'answer' => 'Bằng'],
                    ['q' => 'Số 12 ... số 21?', 'options' => ['Lớn hơn', 'Bé hơn', 'Bằng', 'Không so sánh được'], 'answer' => 'Bé hơn'],
                    ['q' => 'Số 34 ... số 43?', 'options' => ['Lớn hơn', 'Bé hơn', 'Bằng', 'Không so sánh được'], 'answer' => 'Bé hơn'],
                    ['q' => 'Số 99 ... số 100?', 'options' => ['Lớn hơn', 'Bé hơn', 'Bằng', 'Không so sánh được'], 'answer' => 'Bé hơn'],
                    ['q' => 'Số 50 ... số 49?', 'options' => ['Lớn hơn', 'Bé hơn', 'Bằng', 'Không so sánh được'], 'answer' => 'Lớn hơn'],
                    ['q' => 'Số 1 chục ... số 10?', 'options' => ['Lớn hơn', 'Bé hơn', 'Bằng', 'Không so sánh được'], 'answer' => 'Bằng'],
                    ['q' => 'Số 15 ... 1 chục và 5 đơn vị?', 'options' => ['Lớn hơn', 'Bé hơn', 'Bằng', 'Không so sánh được'], 'answer' => 'Bằng'],
                    ['q' => 'Trong các số 19, 91, 29, 92, số nào lớn nhất?', 'options' => ['19', '91', '92', '29'], 'answer' => '92'],
                    ['q' => 'Trong các số 55, 66, 44, 77, số nào bé nhất?', 'options' => ['55', '66', '44', '77'], 'answer' => '44'],
                    ['q' => 'So sánh: 10 + 5 và 14', 'options' => ['Lớn hơn', 'Bé hơn', 'Bằng', 'Không so sánh được'], 'answer' => 'Lớn hơn'],
                    ['q' => 'So sánh: 20 - 1 và 19', 'options' => ['Lớn hơn', 'Bé hơn', 'Bằng', 'Không so sánh được'], 'answer' => 'Bằng'],
                    ['q' => 'Số lớn nhất có hai chữ số là?', 'options' => ['98', '99', '100', '97'], 'answer' => '99'],
                    ['q' => 'Số bé nhất có hai chữ số là?', 'options' => ['0', '10', '11', '9'], 'answer' => '10'],
                    ['q' => 'An có 8 viên bi, Bình có 9 viên bi. Ai có nhiều bi hơn?', 'options' => ['An', 'Bình', 'Bằng nhau', 'Không biết'], 'answer' => 'Bình'],
                ]],
                ['topic' => 'Các dấu =, >, <', 'questions' => [
                    ['q' => 'Phép so sánh nào đúng?', 'options' => ['7 > 10', '7 < 10', '7 = 10', '10 < 7'], 'answer' => '7 < 10'],
                    ['q' => 'Phép so sánh nào đúng?', 'options' => ['15 > 12', '15 < 12', '15 = 12', '12 > 15'], 'answer' => '15 > 12'],
                    ['q' => 'Phép so sánh nào đúng?', 'options' => ['25 > 25', '25 < 25', '25 = 25', 'Không có'], 'answer' => '25 = 25'],
                    ['q' => 'Phép so sánh nào sai?', 'options' => ['99 < 100', '100 > 99', '99 > 100', '99 = 99'], 'answer' => '99 > 100'],
                    ['q' => 'Phép so sánh nào đúng cho "10 + 2 ... 12"?', 'options' => ['>', '<', '=', 'Không so sánh được'], 'answer' => '='],
                    ['q' => 'Phép so sánh nào đúng cho "18 - 3 ... 14"?', 'options' => ['>', '<', '=', 'Không so sánh được'], 'answer' => '>'],
                    ['q' => 'Phép so sánh nào sau đây là đúng?', 'options' => ['3 > 5', '8 < 6', '9 > 7', '4 = 5'], 'answer' => '9 > 7'],
                    ['q' => 'Phép so sánh nào sau đây là sai?', 'options' => ['10 < 20', '15 = 15', '2 > 12', '8 > 7'], 'answer' => '2 > 12'],
                    ['q' => 'Phép so sánh nào đúng cho "5 chục ... 49"?', 'options' => ['>', '<', '=', 'Không so sánh được'], 'answer' => '>'],
                    ['q' => 'Phép so sánh nào đúng cho "34 ... 4 chục"?', 'options' => ['>', '<', '=', 'Không so sánh được'], 'answer' => '<'],
                    ['q' => 'Phép so sánh nào đúng cho "11 + 5 ... 15"?', 'options' => ['>', '<', '=', 'Không so sánh được'], 'answer' => '>'],
                    ['q' => 'Phép so sánh nào đúng cho "20 - 10 ... 10"?', 'options' => ['>', '<', '=', 'Không so sánh được'], 'answer' => '='],
                    ['q' => 'Dấu "<" có nghĩa là gì?', 'options' => ['Lớn hơn', 'Bé hơn', 'Bằng', 'Khác'], 'answer' => 'Bé hơn'],
                    ['q' => 'Dấu ">" có nghĩa là gì?', 'options' => ['Lớn hơn', 'Bé hơn', 'Bằng', 'Khác'], 'answer' => 'Lớn hơn'],
                    ['q' => 'Phép so sánh nào đúng cho "số liền trước của 10 ... 10"?', 'options' => ['>', '<', '=', 'Không so sánh được'], 'answer' => '<'],
                ]],
                ['topic' => 'Số 0 và Số 10', 'questions' => [
                    ['q' => 'Khi trong giỏ không có quả táo nào, ta nói có ... quả táo.', 'options' => ['1', '0', '10', '-1'], 'answer' => '0'],
                    ['q' => 'Số 10 gồm 1 chục và ... đơn vị.', 'options' => ['1', '10', '0', '2'], 'answer' => '0'],
                    ['q' => 'Số liền sau của số 9 là số nào?', 'options' => ['8', '10', '11', '9'], 'answer' => '10'],
                    ['q' => '5 + 0 = ?', 'options' => ['0', '5', '50', '4'], 'answer' => '5'],
                    ['q' => '8 - 8 = ?', 'options' => ['0', '1', '8', '16'], 'answer' => '0'],
                    ['q' => 'Số 0 có phải là số tự nhiên không?', 'options' => ['Có', 'Không', 'Tùy trường hợp', 'Không xác định'], 'answer' => 'Có'],
                    ['q' => 'Số bé nhất có hai chữ số là?', 'options' => ['0', '10', '11', '99'], 'answer' => '10'],
                    ['q' => '7 - 0 = ?', 'options' => ['0', '7', 'Không tính được', '6'], 'answer' => '7'],
                    ['q' => '10 - 10 = ?', 'options' => ['0', '1', '10', '20'], 'answer' => '0'],
                    ['q' => 'Trên cây có 5 con chim, không có con nào bay đến thêm. Trên cây có bao nhiêu con chim?', 'options' => ['0', '5', '6', '10'], 'answer' => '5'],
                    ['q' => 'Số đứng liền trước số 1 là?', 'options' => ['0', '2', 'Không có', '-1'], 'answer' => '0'],
                    ['q' => '10 que tính bó lại thành?', 'options' => ['1 đơn vị', '1 chục', '1 trăm', '10 đơn vị'], 'answer' => '1 chục'],
                    ['q' => 'Số nào lớn hơn: 0 hay 10?', 'options' => ['0', '10', 'Bằng nhau', 'Không so sánh được'], 'answer' => '10'],
                    ['q' => 'Gộp 10 và 0 được mấy?', 'options' => ['0', '10', '100', '11'], 'answer' => '10'],
                    ['q' => 'Số 10 có mấy chữ số?', 'options' => ['1', '2', '3', '0'], 'answer' => '2'],
                ]],
                ['topic' => 'Phép cộng trong phạm vi 10', 'questions' => [
                    ['q' => '5 + 4 = ?', 'options' => ['8', '9', '10', '7'], 'answer' => '9'],
                    ['q' => 'Có 6 cái kẹo, mẹ cho thêm 3 cái nữa. Hỏi có tất cả bao nhiêu cái kẹo?', 'options' => ['8 cái', '9 cái', '10 cái', '3 cái'], 'answer' => '9 cái'],
                    ['q' => '7 + 2 = ?', 'options' => ['8', '9', '10', '5'], 'answer' => '9'],
                    ['q' => '1 + 8 = ?', 'options' => ['7', '8', '9', '10'], 'answer' => '9'],
                    ['q' => 'Kết quả của phép cộng được gọi là gì?', 'options' => ['Hiệu', 'Tổng', 'Tích', 'Thương'], 'answer' => 'Tổng'],
                    ['q' => 'Trong phép tính 3 + 5 = 8, số 3 và 5 được gọi là gì?', 'options' => ['Số hạng', 'Tổng', 'Hiệu', 'Số bị trừ'], 'answer' => 'Số hạng'],
                    ['q' => 'Phép tính nào có tổng bằng 10?', 'options' => ['5 + 4', '6 + 4', '7 + 2', '8 + 1'], 'answer' => '6 + 4'],
                    ['q' => 'An có 4 quả bóng, Bình có 4 quả bóng. Cả hai bạn có mấy quả bóng?', 'options' => ['4', '6', '8', '10'], 'answer' => '8'],
                    ['q' => '2 + 3 + 1 = ?', 'options' => ['5', '6', '7', '4'], 'answer' => '6'],
                    ['q' => 'Điền số thích hợp: 5 + ... = 7', 'options' => ['1', '2', '3', '4'], 'answer' => '2'],
                    ['q' => 'Điền số thích hợp: ... + 6 = 9', 'options' => ['1', '2', '3', '4'], 'answer' => '3'],
                    ['q' => 'Phép tính nào có kết quả lớn nhất?', 'options' => ['2 + 7', '3 + 5', '4 + 6', '1 + 8'], 'answer' => '4 + 6'],
                    ['q' => 'Phép tính nào có kết quả bé nhất?', 'options' => ['1 + 1', '1 + 2', '2 + 2', '0 + 3'], 'answer' => '1 + 1'],
                    ['q' => 'Trên bàn có 5 quyển vở, mẹ đặt thêm 5 quyển vở nữa. Hỏi trên bàn có tất cả bao nhiêu quyển vở?', 'options' => ['5', '10', '15', '0'], 'answer' => '10'],
                    ['q' => 'Khi đổi chỗ các số hạng trong một tổng thì tổng có thay đổi không?', 'options' => ['Có', 'Không', 'Tùy trường hợp', 'Luôn luôn tăng'], 'answer' => 'Không'],
                ]],
                ['topic' => 'Phép trừ trong phạm vi 10', 'questions' => [
                    ['q' => '9 - 7 = ?', 'options' => ['1', '2', '3', '16'], 'answer' => '2'],
                    ['q' => 'Trên cành có 8 con chim, bay đi mất 3 con. Hỏi còn lại mấy con?', 'options' => ['5 con', '6 con', '7 con', '11 con'], 'answer' => '5 con'],
                    ['q' => '10 - 4 = ?', 'options' => ['5', '6', '7', '14'], 'answer' => '6'],
                    ['q' => '8 - 2 = ?', 'options' => ['5', '6', '7', '10'], 'answer' => '6'],
                    ['q' => 'Kết quả của phép trừ được gọi là gì?', 'options' => ['Tổng', 'Hiệu', 'Tích', 'Thương'], 'answer' => 'Hiệu'],
                    ['q' => 'Trong phép tính 9 - 5 = 4, số 9 được gọi là gì?', 'options' => ['Số bị trừ', 'Số trừ', 'Hiệu', 'Số hạng'], 'answer' => 'Số bị trừ'],
                    ['q' => 'Trong phép tính 9 - 5 = 4, số 5 được gọi là gì?', 'options' => ['Số bị trừ', 'Số trừ', 'Hiệu', 'Số hạng'], 'answer' => 'Số trừ'],
                    ['q' => 'Phép tính nào có hiệu bằng 5?', 'options' => ['10 - 4', '9 - 4', '8 - 2', '7 - 1'], 'answer' => '9 - 4'],
                    ['q' => 'An có 10 viên bi, An cho Bình 3 viên. Hỏi An còn lại mấy viên bi?', 'options' => ['6', '7', '8', '13'], 'answer' => '7'],
                    ['q' => '7 - 3 - 1 = ?', 'options' => ['3', '4', '5', '2'], 'answer' => '3'],
                    ['q' => 'Điền số thích hợp: 8 - ... = 2', 'options' => ['4', '5', '6', '10'], 'answer' => '6'],
                    ['q' => 'Điền số thích hợp: ... - 5 = 5', 'options' => ['0', '5', '10', '1'], 'answer' => '10'],
                    ['q' => 'Phép tính nào có kết quả lớn nhất?', 'options' => ['10 - 1', '9 - 2', '8 - 3', '10 - 2'], 'answer' => '10 - 1'],
                    ['q' => 'Phép tính nào có kết quả bé nhất?', 'options' => ['5 - 4', '3 - 1', '2 - 2', '1 - 0'], 'answer' => '2 - 2'],
                    ['q' => 'So sánh: 9 - 3 và 5', 'options' => ['>', '<', '=', 'Không so sánh được'], 'answer' => '>'],
                ]],
                ['topic' => 'Các số đến 20', 'questions' => [
                    ['q' => 'Số "mười bảy" được viết là?', 'options' => ['107', '17', '71', '10'], 'answer' => '17'],
                    ['q' => 'Số liền trước của 20 là số nào?', 'options' => ['10', '19', '21', '18'], 'answer' => '19'],
                    ['q' => 'Số liền sau của 15 là?', 'options' => ['14', '16', '17', '15'], 'answer' => '16'],
                    ['q' => 'Số 12 gồm mấy chục và mấy đơn vị?', 'options' => ['1 chục và 2 đơn vị', '2 chục và 1 đơn vị', '12 đơn vị', '10 chục và 2 đơn vị'], 'answer' => '1 chục và 2 đơn vị'],
                    ['q' => 'Số đứng giữa 18 và 20 là?', 'options' => ['17', '19', '21', '18'], 'answer' => '19'],
                    ['q' => 'Số 19 đọc là?', 'options' => ['Mười chín', 'Một chín', 'Chín mươi một', 'Mười lăm'], 'answer' => 'Mười chín'],
                    ['q' => 'So sánh 13 và 15', 'options' => ['13 > 15', '13 < 15', '13 = 15', 'Không so sánh được'], 'answer' => '13 < 15'],
                    ['q' => 'Trong các số 11, 20, 15, 18, số nào lớn nhất?', 'options' => ['11', '20', '18', '15'], 'answer' => '20'],
                    ['q' => 'Trong các số 14, 12, 19, 10, số nào bé nhất?', 'options' => ['14', '12', '10', '19'], 'answer' => '10'],
                    ['q' => '10 + 8 = ?', 'options' => ['108', '80', '18', '2'], 'answer' => '18'],
                    ['q' => '15 - 5 = ?', 'options' => ['10', '15', '5', '20'], 'answer' => '10'],
                    ['q' => 'Số nào là số tròn chục trong các số sau?', 'options' => ['12', '15', '20', '18'], 'answer' => '20'],
                    ['q' => 'Có bao nhiêu số từ 11 đến 20?', 'options' => ['9', '10', '11', '8'], 'answer' => '10'],
                    ['q' => '1 chục và 9 đơn vị là số mấy?', 'options' => ['109', '91', '19', '10'], 'answer' => '19'],
                    ['q' => 'Số liền trước của 11 là?', 'options' => ['10', '12', '9', '11'], 'answer' => '10'],
                ]],
                ['topic' => 'Các phép tính dạng 10 + 4, 14 - 4', 'questions' => [
                    ['q' => '10 + 6 = ?', 'options' => ['16', '60', '106', '4'], 'answer' => '16'],
                    ['q' => '18 - 8 = ?', 'options' => ['8', '10', '18', '26'], 'answer' => '10'],
                    ['q' => '10 + 3 = ?', 'options' => ['13', '30', '103', '7'], 'answer' => '13'],
                    ['q' => '15 - 5 = ?', 'options' => ['5', '10', '15', '20'], 'answer' => '10'],
                    ['q' => '10 + 9 = ?', 'options' => ['19', '90', '109', '1'], 'answer' => '19'],
                    ['q' => '11 - 1 = ?', 'options' => ['1', '10', '11', '12'], 'answer' => '10'],
                    ['q' => 'Phép tính nào có kết quả là 17?', 'options' => ['10 + 6', '10 + 7', '10 + 8', '17 - 7'], 'answer' => '10 + 7'],
                    ['q' => 'Phép tính nào có kết quả là 10?', 'options' => ['12 - 1', '12 - 2', '12 - 3', '10 + 1'], 'answer' => '12 - 2'],
                    ['q' => '1 chục cộng 5 đơn vị bằng?', 'options' => ['15', '51', '6', '105'], 'answer' => '15'],
                    ['q' => '1 chục và 4 đơn vị trừ đi 4 đơn vị bằng?', 'options' => ['1 chục', '4 đơn vị', '14', '0'], 'answer' => '1 chục'],
                    ['q' => '... + 2 = 12', 'options' => ['2', '10', '14', '9'], 'answer' => '10'],
                    ['q' => '16 - ... = 10', 'options' => ['10', '6', '16', '26'], 'answer' => '6'],
                    ['q' => 'So sánh: 10 + 5 và 16', 'options' => ['>', '<', '=', 'Không so sánh được'], 'answer' => '<'],
                    ['q' => 'So sánh: 19 - 9 và 10', 'options' => ['>', '<', '=', 'Không so sánh được'], 'answer' => '='],
                    ['q' => 'Nhà An có 10 quả trứng, mẹ mua thêm 2 quả nữa. Hỏi nhà An có tất cả bao nhiêu quả trứng?', 'options' => ['8', '10', '12', '20'], 'answer' => '12'],
                ]],
                ['topic' => 'Chục - Số tròn chục', 'questions' => [
                    ['q' => 'Số "năm mươi" được viết là?', 'options' => ['5', '15', '50', '500'], 'answer' => '50'],
                    ['q' => '3 chục + 2 chục = ?', 'options' => ['5 chục', '6 chục', '4 chục', '5 đơn vị'], 'answer' => '5 chục'],
                    ['q' => 'Số 70 đọc là?', 'options' => ['Bảy', 'Mười bảy', 'Bảy mươi', 'Bảy không'], 'answer' => 'Bảy mươi'],
                    ['q' => '90 - 40 = ?', 'options' => ['50', '60', '130', '40'], 'answer' => '50'],
                    ['q' => 'Số tròn chục lớn nhất có hai chữ số là?', 'options' => ['90', '99', '100', '80'], 'answer' => '90'],
                    ['q' => 'Số tròn chục bé nhất có hai chữ số là?', 'options' => ['0', '10', '20', '1'], 'answer' => '10'],
                    ['q' => 'Các số tròn chục là các số có chữ số hàng đơn vị là?', 'options' => ['0', '5', '9', '1'], 'answer' => '0'],
                    ['q' => 'Trong các số 20, 25, 30, 35, số nào là số tròn chục?', 'options' => ['25', '30', '35', 'Tất cả'], 'answer' => '30'],
                    ['q' => 'Số liền sau của 30 là?', 'options' => ['29', '31', '40', '20'], 'answer' => '31'],
                    ['q' => 'Số liền trước của 60 là?', 'options' => ['50', '59', '61', '70'], 'answer' => '59'],
                    ['q' => 'So sánh 80 và 7 chục', 'options' => ['>', '<', '=', 'Không so sánh được'], 'answer' => '>'],
                    ['q' => '6 chục - 1 chục = ?', 'options' => ['5', '50', '70', '61'], 'answer' => '50'],
                    ['q' => 'Có 40 quyển vở, thêm 10 quyển vở nữa. Có tất cả bao nhiêu quyển vở?', 'options' => ['30', '50', '41', '401'], 'answer' => '50'],
                    ['q' => '20 + 30 + 10 = ?', 'options' => ['50', '60', '70', '51'], 'answer' => '60'],
                    ['q' => 'Số gồm 8 chục và 0 đơn vị là?', 'options' => ['8', '80', '800', '808'], 'answer' => '80'],
                ]],
                ['topic' => 'Các số đến 100', 'questions' => [
                    ['q' => 'Số "tám mươi sáu" được viết là?', 'options' => ['68', '806', '86', '80'], 'answer' => '86'],
                    ['q' => 'Số lớn nhất có hai chữ số là?', 'options' => ['90', '99', '100', '98'], 'answer' => '99'],
                    ['q' => 'Số 54 gồm mấy chục và mấy đơn vị?', 'options' => ['5 chục và 4 đơn vị', '4 chục và 5 đơn vị', '50 chục và 4 đơn vị', '9 đơn vị'], 'answer' => '5 chục và 4 đơn vị'],
                    ['q' => 'Số liền trước của 70 là?', 'options' => ['60', '69', '71', '80'], 'answer' => '69'],
                    ['q' => 'Số liền sau của 99 là?', 'options' => ['98', '100', '101', '90'], 'answer' => '100'],
                    ['q' => 'Trong các số 45, 54, 39, 93, số nào lớn nhất?', 'options' => ['54', '39', '93', '45'], 'answer' => '93'],
                    ['q' => 'Số 31 đọc là?', 'options' => ['Ba một', 'Ba mươi mốt', 'Mười ba', 'Ba mươi'], 'answer' => 'Ba mươi mốt'],
                    ['q' => 'So sánh 87 và 78', 'options' => ['87 > 78', '87 < 78', '87 = 78', 'Không so sánh được'], 'answer' => '87 > 78'],
                    ['q' => 'Số bé nhất có hai chữ số giống nhau là?', 'options' => ['10', '11', '22', '00'], 'answer' => '11'],
                    ['q' => 'Số gồm 6 chục và 0 đơn vị là?', 'options' => ['6', '60', '600', '610'], 'answer' => '60'],
                    ['q' => '45 + 12 = ?', 'options' => ['55', '57', '59', '33'], 'answer' => '57'],
                    ['q' => '78 - 25 = ?', 'options' => ['53', '54', '55', '103'], 'answer' => '53'],
                    ['q' => 'Số đứng giữa 68 và 70 là?', 'options' => ['67', '69', '71', '68'], 'answer' => '69'],
                    ['q' => 'Có bao nhiêu số có hai chữ số?', 'options' => ['89', '90', '99', '100'], 'answer' => '90'],
                    ['q' => 'Số bé nhất có hai chữ số mà chữ số hàng chục là 5?', 'options' => ['51', '50', '55', '15'], 'answer' => '50'],
                ]],
                ['topic' => 'Bảng các số từ 1 đến 100', 'questions' => [
                    ['q' => 'Trong bảng các số từ 1 đến 100, số đứng ngay sau số 55 là?', 'options' => ['54', '56', '65', '50'], 'answer' => '56'],
                    ['q' => 'Số 99 đứng ở đâu trong bảng các số?', 'options' => ['Hàng cuối cùng', 'Hàng đầu tiên', 'Hàng giữa', 'Cột đầu tiên'], 'answer' => 'Hàng cuối cùng'],
                    ['q' => 'Số đứng ngay trước số 21 là?', 'options' => ['20', '22', '31', '12'], 'answer' => '20'],
                    ['q' => 'Số ở góc dưới cùng bên phải của bảng là?', 'options' => ['90', '99', '100', '10'], 'answer' => '100'],
                    ['q' => 'Số 1 nằm ở đâu?', 'options' => ['Hàng đầu, cột đầu', 'Hàng cuối, cột cuối', 'Giữa bảng', 'Hàng đầu, cột cuối'], 'answer' => 'Hàng đầu, cột đầu'],
                    ['q' => 'Trong hàng thứ 3 (từ 21 đến 30), số lớn nhất là?', 'options' => ['21', '29', '30', '25'], 'answer' => '30'],
                    ['q' => 'Tất cả các số trong cột thứ 5 có chữ số hàng đơn vị là?', 'options' => ['4', '5', '6', '10'], 'answer' => '5'],
                    ['q' => 'Số 44 nằm ở hàng thứ mấy?', 'options' => ['4', '5', '6', '3'], 'answer' => '5'],
                    ['q' => 'Số nào nằm ngay dưới số 37?', 'options' => ['36', '38', '47', '27'], 'answer' => '47'],
                    ['q' => 'Số nào nằm ngay trên số 82?', 'options' => ['81', '83', '72', '92'], 'answer' => '72'],
                    ['q' => 'Có bao nhiêu số có hai chữ số giống nhau trong bảng?', 'options' => ['8', '9', '10', '11'], 'answer' => '9'],
                    ['q' => 'Có bao nhiêu số có chữ số 0 ở hàng đơn vị?', 'options' => ['9', '10', '11', '1'], 'answer' => '10'],
                    ['q' => 'Số bé nhất có hai chữ số trong bảng là?', 'options' => ['1', '10', '11', '99'], 'answer' => '10'],
                    ['q' => 'Số 73 gồm mấy chục và mấy đơn vị?', 'options' => ['7 chục, 3 đơn vị', '3 chục, 7 đơn vị', '73 đơn vị', '10 đơn vị'], 'answer' => '7 chục, 3 đơn vị'],
                    ['q' => 'Số đứng liền trước và liền sau của 50 là?', 'options' => ['40 và 60', '49 và 51', '45 và 55', '51 và 52'], 'answer' => '49 và 51'],
                ]],
                ['topic' => 'Các phép tính dạng 34 + 23, 57 - 23', 'questions' => [
                    ['q' => '41 + 15 = ?', 'options' => ['55', '56', '57', '66'], 'answer' => '56'],
                    ['q' => '88 - 35 = ?', 'options' => ['53', '54', '55', '123'], 'answer' => '53'],
                    ['q' => '26 + 52 = ?', 'options' => ['77', '78', '79', '24'], 'answer' => '78'],
                    ['q' => '97 - 64 = ?', 'options' => ['31', '32', '33', '161'], 'answer' => '33'],
                    ['q' => 'Khi cộng không nhớ, ta cộng hàng nào trước?', 'options' => ['Hàng chục', 'Hàng đơn vị', 'Hàng nào cũng được', 'Hàng trăm'], 'answer' => 'Hàng đơn vị'],
                    ['q' => 'Khi trừ không nhớ, ta trừ hàng nào trước?', 'options' => ['Hàng chục', 'Hàng đơn vị', 'Hàng nào cũng được', 'Hàng trăm'], 'answer' => 'Hàng đơn vị'],
                    ['q' => '30 + 40 = ?', 'options' => ['60', '70', '80', '10'], 'answer' => '70'],
                    ['q' => '60 - 20 = ?', 'options' => ['30', '40', '50', '80'], 'answer' => '40'],
                    ['q' => 'Số hạng thứ nhất là 25, số hạng thứ hai là 14. Tổng là?', 'options' => ['38', '39', '40', '11'], 'answer' => '39'],
                    ['q' => 'Số bị trừ là 75, số trừ là 25. Hiệu là?', 'options' => ['50', '55', '100', '40'], 'answer' => '50'],
                    ['q' => 'Lớp 1A có 22 bạn nam và 15 bạn nữ. Hỏi lớp 1A có tất cả bao nhiêu bạn?', 'options' => ['35 bạn', '36 bạn', '37 bạn', '7 bạn'], 'answer' => '37 bạn'],
                    ['q' => 'Thùng cam có 48 quả, đã bán đi 16 quả. Hỏi còn lại bao nhiêu quả?', 'options' => ['31 quả', '32 quả', '33 quả', '64 quả'], 'answer' => '32 quả'],
                    ['q' => 'Tìm x, biết x - 12 = 34', 'options' => ['22', '46', '48', '40'], 'answer' => '46'],
                    ['q' => 'Tìm y, biết y + 21 = 55', 'options' => ['34', '76', '33', '24'], 'answer' => '34'],
                    ['q' => '55 + 44 = ?', 'options' => ['98', '99', '100', '11'], 'answer' => '99'],
                ]],
                ['topic' => 'Các ngày trong tuần', 'questions' => [
                    ['q' => 'Một tuần có mấy ngày?', 'options' => ['5 ngày', '6 ngày', '7 ngày', '8 ngày'], 'answer' => '7 ngày'],
                    ['q' => 'Hôm nay là Chủ nhật, ngày mai là thứ mấy?', 'options' => ['Thứ Bảy', 'Thứ Hai', 'Thứ Ba', 'Chủ nhật'], 'answer' => 'Thứ Hai'],
                    ['q' => 'Ngày đầu tiên đi học trong tuần là thứ mấy?', 'options' => ['Thứ Hai', 'Thứ Ba', 'Chủ nhật', 'Thứ Bảy'], 'answer' => 'Thứ Hai'],
                    ['q' => 'Ngày cuối tuần là những ngày nào?', 'options' => ['Thứ Sáu, Thứ Bảy', 'Thứ Bảy, Chủ nhật', 'Chủ nhật, Thứ Hai', 'Thứ Năm, Thứ Sáu'], 'answer' => 'Thứ Bảy, Chủ nhật'],
                    ['q' => 'Hôm nay là thứ Năm, hôm qua là thứ mấy?', 'options' => ['Thứ Tư', 'Thứ Sáu', 'Thứ Ba', 'Thứ Năm'], 'answer' => 'Thứ Tư'],
                    ['q' => 'Hôm nay là thứ Sáu, ngày kia là thứ mấy?', 'options' => ['Thứ Bảy', 'Chủ nhật', 'Thứ Hai', 'Thứ Năm'], 'answer' => 'Chủ nhật'],
                    ['q' => 'Tên của 7 ngày trong tuần là gì?', 'options' => ['Thứ 1, 2, 3, 4, 5, 6, 7', 'Thứ Hai, Ba, Tư, Năm, Sáu, Bảy, Chủ nhật', 'Tùy mỗi nơi', 'Ngày 1 đến ngày 7'], 'answer' => 'Thứ Hai, Ba, Tư, Năm, Sáu, Bảy, Chủ nhật'],
                    ['q' => 'Nếu hôm nay là 1/1 và là Thứ Hai, thì ngày 3/1 là thứ mấy?', 'options' => ['Thứ Ba', 'Thứ Tư', 'Thứ Năm', 'Thứ Sáu'], 'answer' => 'Thứ Tư'],
                    ['q' => 'Thứ nào đứng ngay sau Thứ Tư?', 'options' => ['Thứ Ba', 'Thứ Năm', 'Thứ Sáu', 'Thứ Hai'], 'answer' => 'Thứ Năm'],
                    ['q' => 'Thứ nào đứng ngay trước Thứ Bảy?', 'options' => ['Thứ Năm', 'Thứ Sáu', 'Chủ nhật', 'Thứ Tám'], 'answer' => 'Thứ Sáu'],
                    ['q' => 'Thứ Tư còn được gọi là?', 'options' => ['Thứ 3', 'Thứ 4', 'Thứ 5', 'Ngày 4'], 'answer' => 'Thứ 4'],
                    ['q' => 'Chủ nhật còn được gọi là?', 'options' => ['Cuối tuần', 'Ngày nghỉ', 'Cả hai đều đúng', 'Ngày lễ'], 'answer' => 'Cả hai đều đúng'],
                    ['q' => 'Bạn An đi học từ thứ Hai đến thứ Sáu. Hỏi bạn An nghỉ mấy ngày trong tuần?', 'options' => ['1 ngày', '2 ngày', '3 ngày', '0 ngày'], 'answer' => '2 ngày'],
                    ['q' => 'Thứ tự đúng là?', 'options' => ['Thứ Hai, Thứ Tư, Thứ Ba', 'Thứ Năm, Thứ Sáu, Thứ Bảy', 'Chủ nhật, Thứ Bảy, Thứ Sáu', 'Thứ Ba, Thứ Năm, Thứ Sáu'], 'answer' => 'Thứ Năm, Thứ Sáu, Thứ Bảy'],
                    ['q' => 'Trong một tuần, có bao nhiêu ngày đi học và bao nhiêu ngày nghỉ?', 'options' => ['5 đi học, 2 nghỉ', '6 đi học, 1 nghỉ', '4 đi học, 3 nghỉ', '7 đi học, 0 nghỉ'], 'answer' => '5 đi học, 2 nghỉ'],
                ]],
            ],
            // ========== LỚP 2 ==========
            2 => [
                ['topic' => 'Ôn tập các số đến 100', 'questions' => [
                    ['q' => 'Số liền sau của 99 là?', 'options' => ['98', '100', '101', '99'], 'answer' => '100'],
                    ['q' => 'Số gồm 7 chục và 2 đơn vị viết là?', 'options' => ['27', '72', '702', '70'], 'answer' => '72'],
                    ['q' => 'Số lớn nhất có hai chữ số là?', 'options' => ['90', '99', '100', '98'], 'answer' => '99'],
                    ['q' => 'Số bé nhất có hai chữ số khác nhau là?', 'options' => ['10', '11', '12', '9'], 'answer' => '10'],
                    ['q' => 'Trong số 85, chữ số 8 có giá trị là?', 'options' => ['8', '80', '85', '5'], 'answer' => '80'],
                    ['q' => 'Đọc số 51', 'options' => ['Năm mốt', 'Năm mươi mốt', 'Năm một', 'Mười lăm'], 'answer' => 'Năm mươi mốt'],
                    ['q' => 'Số tròn chục đứng giữa 40 và 60 là?', 'options' => ['45', '50', '55', '30'], 'answer' => '50'],
                    ['q' => 'Kết quả của 35 + 24 là?', 'options' => ['58', '59', '60', '11'], 'answer' => '59'],
                    ['q' => 'Kết quả của 87 - 31 là?', 'options' => ['55', '56', '57', '118'], 'answer' => '56'],
                    ['q' => 'So sánh 69 và 96', 'options' => ['69 > 96', '69 < 96', '69 = 96', 'Không so sánh được'], 'answer' => '69 < 96'],
                    ['q' => 'Làm tròn số 78 đến hàng chục ta được?', 'options' => ['70', '80', '75', '100'], 'answer' => '80'],
                    ['q' => 'Dãy số được sắp xếp theo thứ tự từ lớn đến bé là?', 'options' => ['19, 28, 54, 45', '54, 45, 28, 19', '19, 54, 28, 45', '54, 28, 45, 19'], 'answer' => '54, 45, 28, 19'],
                    ['q' => 'Số liền trước của 100 là?', 'options' => ['90', '99', '101', '98'], 'answer' => '99'],
                    ['q' => 'Tìm x, biết x + 20 = 50', 'options' => ['30', '70', '25', '40'], 'answer' => '30'],
                    ['q' => 'Tìm y, biết 60 - y = 40', 'options' => ['100', '30', '20', '50'], 'answer' => '20'],
                ]],
                ['topic' => 'Số hạng – Tổng', 'questions' => [
                    ['q' => 'Trong phép tính 25 + 14 = 39, số 39 được gọi là gì?', 'options' => ['Số hạng', 'Tổng', 'Hiệu', 'Số bị trừ'], 'answer' => 'Tổng'],
                    ['q' => 'Biết hai số hạng là 30 và 40. Tổng là?', 'options' => ['10', '70', '120', '3040'], 'answer' => '70'],
                    ['q' => 'Trong phép tính 52 + 18 = 70, số 52 được gọi là gì?', 'options' => ['Tổng', 'Số hạng', 'Số bị trừ', 'Hiệu'], 'answer' => 'Số hạng'],
                    ['q' => 'Muốn tìm tổng ta làm thế nào?', 'options' => ['Số hạng + số hạng', 'Số hạng - số hạng', 'Tổng - số hạng', 'Hiệu + số trừ'], 'answer' => 'Số hạng + số hạng'],
                    ['q' => 'Tổng của 45 và 20 là?', 'options' => ['25', '65', '75', '4520'], 'answer' => '65'],
                    ['q' => 'Nếu ta đổi chỗ các số hạng trong một tổng thì tổng sẽ?', 'options' => ['Thay đổi', 'Không thay đổi', 'Tăng lên', 'Giảm đi'], 'answer' => 'Không thay đổi'],
                    ['q' => 'Phép tính 17 + 23 có tổng là?', 'options' => ['30', '40', '50', '310'], 'answer' => '40'],
                    ['q' => 'Tìm một số hạng, biết tổng là 50 và số hạng kia là 22.', 'options' => ['28', '38', '72', '22'], 'answer' => '28'],
                    ['q' => 'Tổng của số chẵn lớn nhất có một chữ số và 12 là?', 'options' => ['18', '20', '22', '21'], 'answer' => '20'],
                    ['q' => 'Một cửa hàng buổi sáng bán được 35 quyển vở, buổi chiều bán được 42 quyển. Tổng số vở bán được là?', 'options' => ['76 quyển', '77 quyển', '78 quyển', '7 quyển'], 'answer' => '77 quyển'],
                    ['q' => 'Trong phép cộng, các số đem cộng gọi là gì?', 'options' => ['Số trừ', 'Số hạng', 'Tổng', 'Số bị trừ'], 'answer' => 'Số hạng'],
                    ['q' => 'Kết quả của phép cộng gọi là gì?', 'options' => ['Hiệu', 'Tích', 'Tổng', 'Thương'], 'answer' => 'Tổng'],
                    ['q' => 'Tổng của 31 và 19 là?', 'options' => ['40', '50', '60', '49'], 'answer' => '50'],
                    ['q' => 'Một số hạng là 25, tổng là 60. Số hạng còn lại là?', 'options' => ['35', '45', '85', '25'], 'answer' => '35'],
                    ['q' => 'So sánh: 25 + 10 và 10 + 25', 'options' => ['>', '<', '=', 'Không so sánh được'], 'answer' => '='],
                ]],
                ['topic' => 'Số bị trừ – Số trừ – Hiệu', 'questions' => [
                    ['q' => 'Trong phép tính 86 - 25 = 61, số 86 được gọi là gì?', 'options' => ['Số bị trừ', 'Số trừ', 'Hiệu', 'Tổng'], 'answer' => 'Số bị trừ'],
                    ['q' => 'Hiệu của 50 và 20 là?', 'options' => ['30', '70', '100', '25'], 'answer' => '30'],
                    ['q' => 'Trong phép tính 78 - 32 = 46, số 32 được gọi là gì?', 'options' => ['Số bị trừ', 'Số trừ', 'Hiệu', 'Số hạng'], 'answer' => 'Số trừ'],
                    ['q' => 'Kết quả của phép trừ 90 - 45 là?', 'options' => ['45', '55', '135', '40'], 'answer' => '45'],
                    ['q' => 'Muốn tìm số bị trừ ta làm thế nào?', 'options' => ['Hiệu + Số trừ', 'Hiệu - Số trừ', 'Số trừ - Hiệu', 'Số bị trừ - Số trừ'], 'answer' => 'Hiệu + Số trừ'],
                    ['q' => 'Muốn tìm số trừ ta làm thế nào?', 'options' => ['Số bị trừ + Hiệu', 'Số bị trừ - Hiệu', 'Hiệu - Số bị trừ', 'Tổng - Số hạng'], 'answer' => 'Số bị trừ - Hiệu'],
                    ['q' => 'Tìm x, biết x - 25 = 30', 'options' => ['5', '55', '65', '25'], 'answer' => '55'],
                    ['q' => 'Tìm y, biết 70 - y = 15', 'options' => ['85', '55', '65', '70'], 'answer' => '55'],
                    ['q' => 'Hiệu của số lớn nhất có hai chữ số và 50 là?', 'options' => ['40', '49', '149', '50'], 'answer' => '49'],
                    ['q' => 'Một sợi dây dài 95cm, cắt đi 35cm. Sợi dây còn lại dài bao nhiêu?', 'options' => ['50cm', '60cm', '130cm', '95cm'], 'answer' => '60cm'],
                    ['q' => 'Kết quả của phép trừ được gọi là gì?', 'options' => ['Tổng', 'Hiệu', 'Số trừ', 'Số bị trừ'], 'answer' => 'Hiệu'],
                    ['q' => 'Số đứng trước dấu trừ gọi là gì?', 'options' => ['Số trừ', 'Số bị trừ', 'Hiệu', 'Số hạng'], 'answer' => 'Số bị trừ'],
                    ['q' => 'Số đứng sau dấu trừ gọi là gì?', 'options' => ['Số trừ', 'Số bị trừ', 'Hiệu', 'Số hạng'], 'answer' => 'Số trừ'],
                    ['q' => 'So sánh: 50 - 10 và 30', 'options' => ['>', '<', '=', 'Không so sánh được'], 'answer' => '>'],
                    ['q' => 'So sánh: 80 - 25 và 55', 'options' => ['>', '<', '=', 'Không so sánh được'], 'answer' => '='],
                ]],
                ['topic' => 'Điểm – Đoạn thẳng', 'questions' => [
                    ['q' => 'Nối hai điểm A và B ta được gì?', 'options' => ['Một điểm', 'Một đường thẳng', 'Đoạn thẳng AB', 'Một tia'], 'answer' => 'Đoạn thẳng AB'],
                    ['q' => 'Đoạn thẳng có bị kéo dài mãi về hai phía không?', 'options' => ['Có', 'Không', 'Chỉ một phía', 'Tùy trường hợp'], 'answer' => 'Không'],
                    ['q' => 'Một dấu chấm nhỏ trên trang giấy là hình ảnh của một ...?', 'options' => ['Đoạn thẳng', 'Điểm', 'Đường thẳng', 'Góc'], 'answer' => 'Điểm'],
                    ['q' => 'Đoạn thẳng AB được giới hạn bởi hai điểm nào?', 'options' => ['A và C', 'B và C', 'A và B', 'Chỉ A'], 'answer' => 'A và B'],
                    ['q' => 'Để vẽ một đoạn thẳng, ta cần dùng dụng cụ gì?', 'options' => ['Com-pa', 'Thước kẻ', 'Kéo', 'Bút màu'], 'answer' => 'Thước kẻ'],
                    ['q' => 'Ba điểm A, B, C cùng nằm trên một đường thẳng được gọi là?', 'options' => ['Ba điểm thẳng hàng', 'Ba điểm không thẳng hàng', 'Tam giác', 'Ba điểm cong'], 'answer' => 'Ba điểm thẳng hàng'],
                    ['q' => 'Độ dài của một đoạn thẳng là?', 'options' => ['Vô hạn', 'Có thể đo được', 'Không xác định', 'Bằng 0'], 'answer' => 'Có thể đo được'],
                    ['q' => 'Trên một đoạn thẳng, ta có thể lấy bao nhiêu điểm?', 'options' => ['Chỉ 2 điểm', 'Chỉ 3 điểm', 'Vô số điểm', '1 điểm'], 'answer' => 'Vô số điểm'],
                    ['q' => 'Hình tam giác có mấy đoạn thẳng?', 'options' => ['2', '3', '4', '1'], 'answer' => '3'],
                    ['q' => 'Hình vuông được tạo bởi mấy đoạn thẳng bằng nhau?', 'options' => ['2', '3', '4', '5'], 'answer' => '4'],
                    ['q' => 'Điểm nằm giữa hai điểm A và B trên một đoạn thẳng thì?', 'options' => ['A, B và điểm đó thẳng hàng', 'Tạo thành tam giác', 'Không có quan hệ', 'Tạo thành góc'], 'answer' => 'A, B và điểm đó thẳng hàng'],
                    ['q' => 'Để đặt tên cho một điểm, người ta thường dùng?', 'options' => ['Chữ cái in hoa', 'Chữ cái in thường', 'Con số', 'Ký hiệu đặc biệt'], 'answer' => 'Chữ cái in hoa'],
                    ['q' => 'Để đặt tên cho một đoạn thẳng có hai đầu mút là M và N, ta gọi là?', 'options' => ['Đoạn thẳng M', 'Đoạn thẳng MN', 'Đoạn thẳng m', 'Đường M'], 'answer' => 'Đoạn thẳng MN'],
                    ['q' => 'Đoạn thẳng AB dài 5cm, đoạn thẳng CD dài 7cm. Tổng độ dài hai đoạn thẳng là?', 'options' => ['10cm', '12cm', '15cm', '2cm'], 'answer' => '12cm'],
                    ['q' => 'Đoạn thẳng PQ dài 10cm, đoạn thẳng RS ngắn hơn 3cm. Đoạn thẳng RS dài?', 'options' => ['7cm', '13cm', '3cm', '10cm'], 'answer' => '7cm'],
                ]],
                ['topic' => 'Đề-xi-mét', 'questions' => [
                    ['q' => '1 dm bằng bao nhiêu cm?', 'options' => ['1 cm', '10 cm', '100 cm', '0.1 cm'], 'answer' => '10 cm'],
                    ['q' => '30 cm đổi ra đề-xi-mét là?', 'options' => ['3 dm', '30 dm', '300 dm', '0.3 dm'], 'answer' => '3 dm'],
                    ['q' => 'Đề-xi-mét được viết tắt là gì?', 'options' => ['cm', 'dm', 'm', 'dxm'], 'answer' => 'dm'],
                    ['q' => 'Vật nào sau đây dài khoảng 1 dm?', 'options' => ['Cục tẩy', 'Cái bút bi', 'Cái bảng', 'Sân trường'], 'answer' => 'Cái bút bi'],
                    ['q' => 'So sánh: 5 dm và 45 cm', 'options' => ['5 dm > 45 cm', '5 dm < 45 cm', '5 dm = 45 cm', 'Không so sánh được'], 'answer' => '5 dm > 45 cm'],
                    ['q' => '2 dm 5 cm bằng bao nhiêu cm?', 'options' => ['25 cm', '205 cm', '7 cm', '3 cm'], 'answer' => '25 cm'],
                    ['q' => '1 mét bằng bao nhiêu đề-xi-mét?', 'options' => ['1 dm', '10 dm', '100 dm', '0.1 dm'], 'answer' => '10 dm'],
                    ['q' => 'Thước kẻ của học sinh thường dài 20cm, tức là dài bao nhiêu dm?', 'options' => ['1 dm', '2 dm', '20 dm', '0.2 dm'], 'answer' => '2 dm'],
                    ['q' => 'Sợi dây dài 1dm, cắt đi 3cm. Sợi dây còn lại dài?', 'options' => ['7 dm', '7 cm', '13 cm', '2 dm'], 'answer' => '7 cm'],
                    ['q' => 'Đơn vị nào lớn hơn đề-xi-mét?', 'options' => ['Mét', 'Xăng-ti-mét', 'Mi-li-mét', 'Không có'], 'answer' => 'Mét'],
                    ['q' => 'Đơn vị nào nhỏ hơn đề-xi-mét?', 'options' => ['Mét', 'Xăng-ti-mét', 'Ki-lô-mét', 'Tấn'], 'answer' => 'Xăng-ti-mét'],
                    ['q' => '5 dm + 3 dm = ?', 'options' => ['8 cm', '8 dm', '80 dm', '2 dm'], 'answer' => '8 dm'],
                    ['q' => '10 dm - 4 dm = ?', 'options' => ['6 dm', '6 cm', '14 dm', '5 dm'], 'answer' => '6 dm'],
                    ['q' => 'Sắp xếp theo thứ tự từ bé đến lớn: 1m, 5dm, 80cm', 'options' => ['1m, 5dm, 80cm', '5dm, 80cm, 1m', '80cm, 1m, 5dm', '5dm, 1m, 80cm'], 'answer' => '5dm, 80cm, 1m'],
                    ['q' => '4 dm = ... cm?', 'options' => ['4 cm', '40 cm', '400 cm', '0.4 cm'], 'answer' => '40 cm'],
                ]],
                ['topic' => '9 cộng với một số', 'questions' => [
                    ['q' => '9 + 5 = ?', 'options' => ['13', '14', '15', '4'], 'answer' => '14'],
                    ['q' => '9 + 7 = ?', 'options' => ['15', '16', '17', '2'], 'answer' => '16'],
                    ['q' => 'Kết quả của 9 + 3 là?', 'options' => ['11', '12', '13', '6'], 'answer' => '12'],
                    ['q' => 'Lớp 2A có 9 bạn nam và 8 bạn nữ. Lớp có tất cả bao nhiêu bạn?', 'options' => ['16 bạn', '17 bạn', '18 bạn', '1 bạn'], 'answer' => '17 bạn'],
                    ['q' => '9 + 9 = ?', 'options' => ['17', '18', '19', '0'], 'answer' => '18'],
                    ['q' => 'Để tính 9 + a, ta có thể lấy 10 cộng với số nào?', 'options' => ['a', 'a - 1', 'a + 1', '10'], 'answer' => 'a - 1'],
                    ['q' => '9 + 2 = ?', 'options' => ['10', '11', '12', '7'], 'answer' => '11'],
                    ['q' => '9 + 4 = ?', 'options' => ['12', '13', '14', '5'], 'answer' => '13'],
                    ['q' => '9 + 6 = ?', 'options' => ['14', '15', '16', '3'], 'answer' => '15'],
                    ['q' => 'Một đàn gà có 9 con gà mái và 5 con gà trống. Đàn gà có tất cả bao nhiêu con?', 'options' => ['13 con', '14 con', '15 con', '4 con'], 'answer' => '14 con'],
                    ['q' => 'Tìm x, biết x - 9 = 5', 'options' => ['4', '13', '14', '5'], 'answer' => '14'],
                    ['q' => 'So sánh: 9 + 6 và 15', 'options' => ['>', '<', '=', 'Không so sánh được'], 'answer' => '='],
                    ['q' => 'So sánh: 9 + 4 và 12', 'options' => ['>', '<', '=', 'Không so sánh được'], 'answer' => '>'],
                    ['q' => 'Điền số thích hợp: 9 + ... = 17', 'options' => ['6', '7', '8', '9'], 'answer' => '8'],
                    ['q' => 'Phép tính nào có kết quả lớn nhất?', 'options' => ['9 + 2', '9 + 5', '9 + 8', '9 + 1'], 'answer' => '9 + 8'],
                ]],
                ['topic' => 'Bảng cộng', 'questions' => [
                    ['q' => '8 + 6 = ?', 'options' => ['13', '14', '15', '12'], 'answer' => '14'],
                    ['q' => '7 + 5 = ?', 'options' => ['11', '12', '13', '10'], 'answer' => '12'],
                    ['q' => '6 + 7 = ?', 'options' => ['12', '13', '14', '11'], 'answer' => '13'],
                    ['q' => '5 + 8 = ?', 'options' => ['12', '13', '14', '11'], 'answer' => '13'],
                    ['q' => '4 + 9 = ?', 'options' => ['12', '13', '14', '11'], 'answer' => '13'],
                    ['q' => '8 + 8 = ?', 'options' => ['15', '16', '17', '14'], 'answer' => '16'],
                    ['q' => '7 + 7 = ?', 'options' => ['13', '14', '15', '12'], 'answer' => '14'],
                    ['q' => '6 + 6 = ?', 'options' => ['11', '12', '13', '10'], 'answer' => '12'],
                    ['q' => '8 + 3 = ?', 'options' => ['10', '11', '12', '9'], 'answer' => '11'],
                    ['q' => '7 + 4 = ?', 'options' => ['10', '11', '12', '9'], 'answer' => '11'],
                    ['q' => '6 + 5 = ?', 'options' => ['10', '11', '12', '9'], 'answer' => '11'],
                    ['q' => '8 + 7 = ?', 'options' => ['14', '15', '16', '13'], 'answer' => '15'],
                    ['q' => '7 + 6 = ?', 'options' => ['12', '13', '14', '11'], 'answer' => '13'],
                    ['q' => '8 + 4 = ?', 'options' => ['11', '12', '13', '10'], 'answer' => '12'],
                    ['q' => '7 + 8 = ?', 'options' => ['14', '15', '16', '13'], 'answer' => '15'],
                ]],
                ['topic' => 'Đường gấp khúc', 'questions' => [
                    ['q' => 'Đường gấp khúc được tạo thành từ nhiều ...?', 'options' => ['Điểm', 'Đoạn thẳng', 'Hình tròn', 'Đường cong'], 'answer' => 'Đoạn thẳng'],
                    ['q' => 'Độ dài đường gấp khúc gồm 2 đoạn dài 8cm và 9cm là?', 'options' => ['16cm', '17cm', '18cm', '1cm'], 'answer' => '17cm'],
                    ['q' => 'Đường gấp khúc ABCD gồm mấy đoạn thẳng?', 'options' => ['2', '3', '4', '1'], 'answer' => '3'],
                    ['q' => 'Muốn tính độ dài đường gấp khúc, ta làm gì?', 'options' => ['Cộng độ dài các đoạn thẳng lại', 'Nhân độ dài các đoạn thẳng', 'Trừ độ dài các đoạn thẳng', 'Chia độ dài các đoạn thẳng'], 'answer' => 'Cộng độ dài các đoạn thẳng lại'],
                    ['q' => 'Một đường gấp khúc có 3 đoạn thẳng, mỗi đoạn dài 5cm. Độ dài đường gấp khúc là?', 'options' => ['10cm', '15cm', '20cm', '5cm'], 'answer' => '15cm'],
                    ['q' => 'Hình ziczac là một dạng của?', 'options' => ['Đường thẳng', 'Đường cong', 'Đường gấp khúc', 'Hình tròn'], 'answer' => 'Đường gấp khúc'],
                    ['q' => 'Chu vi của một hình tam giác có phải là độ dài của một đường gấp khúc khép kín không?', 'options' => ['Có', 'Không', 'Chỉ đôi khi', 'Không liên quan'], 'answer' => 'Có'],
                    ['q' => 'Đường gấp khúc MNPQ có độ dài các đoạn MN=4cm, NP=6cm, PQ=5cm. Độ dài đường gấp khúc MNPQ là?', 'options' => ['14cm', '15cm', '16cm', '10cm'], 'answer' => '15cm'],
                    ['q' => 'Một con kiến bò theo đường gấp khúc có 4 đoạn bằng nhau, tổng độ dài là 20cm. Mỗi đoạn dài bao nhiêu?', 'options' => ['4cm', '5cm', '6cm', '10cm'], 'answer' => '5cm'],
                    ['q' => 'Sự khác biệt chính giữa đường thẳng và đường gấp khúc là gì?', 'options' => ['Đường gấp khúc không thẳng', 'Đường gấp khúc có giới hạn', 'Cả hai đều đúng', 'Không có sự khác biệt'], 'answer' => 'Cả hai đều đúng'],
                    ['q' => 'Đường gấp khúc có thể tự cắt chính nó không?', 'options' => ['Có', 'Không', 'Chỉ trong không gian 3 chiều', 'Chỉ khi nó là đường cong'], 'answer' => 'Có'],
                    ['q' => 'Hình nào không phải là đường gấp khúc?', 'options' => ['Hình vuông', 'Hình tam giác', 'Hình tròn', 'Hình thang'], 'answer' => 'Hình tròn'],
                    ['q' => 'Độ dài đường gấp khúc có thể là 0cm không?', 'options' => ['Có', 'Không', 'Chỉ khi có 1 điểm', 'Tùy vào cách đo'], 'answer' => 'Không'],
                    ['q' => 'Đoạn thẳng có phải là trường hợp đặc biệt của đường gấp khúc không?', 'options' => ['Có (chỉ có 1 đoạn)', 'Không', 'Không liên quan', 'Chỉ khi nó thẳng đứng'], 'answer' => 'Có (chỉ có 1 đoạn)'],
                    ['q' => 'Đường gấp khúc có hai đoạn thẳng dài 1dm và 5cm. Độ dài đường gấp khúc là bao nhiêu cm?', 'options' => ['6cm', '15cm', '105cm', '1.5cm'], 'answer' => '15cm'],
                ]],
                ['topic' => '11 trừ đi một số', 'questions' => [
                    ['q' => '11 - 5 = ?', 'options' => ['5', '6', '7', '16'], 'answer' => '6'],
                    ['q' => 'Có 11 cái kẹo, đã ăn hết 3 cái. Hỏi còn lại bao nhiêu cái?', 'options' => ['7 cái', '8 cái', '9 cái', '14 cái'], 'answer' => '8 cái'],
                    ['q' => '11 - 9 = ?', 'options' => ['1', '2', '3', '20'], 'answer' => '2'],
                    ['q' => '11 - 2 = ?', 'options' => ['8', '9', '10', '13'], 'answer' => '9'],
                    ['q' => 'Hiệu của 11 và 7 là?', 'options' => ['3', '4', '5', '18'], 'answer' => '4'],
                    ['q' => 'Lớp 2B có 11 bạn, trong đó có 6 bạn nữ. Hỏi có bao nhiêu bạn nam?', 'options' => ['4 bạn', '5 bạn', '6 bạn', '17 bạn'], 'answer' => '5 bạn'],
                    ['q' => '11 - 8 = ?', 'options' => ['2', '3', '4', '19'], 'answer' => '3'],
                    ['q' => 'Để tính 11 - a, ta có thể lấy 10 - ? rồi cộng 1', 'options' => ['a', 'a-1', 'a+1', '10'], 'answer' => 'a-1'],
                    ['q' => '11 - 4 = ?', 'options' => ['6', '7', '8', '15'], 'answer' => '7'],
                    ['q' => '11 - 6 = ?', 'options' => ['4', '5', '6', '17'], 'answer' => '5'],
                    ['q' => 'Tìm x, biết x + 7 = 11', 'options' => ['3', '4', '5', '18'], 'answer' => '4'],
                    ['q' => 'Tìm y, biết 11 - y = 9', 'options' => ['1', '2', '3', '20'], 'answer' => '2'],
                    ['q' => 'So sánh: 11 - 3 và 8', 'options' => ['>', '<', '=', 'Không so sánh được'], 'answer' => '='],
                    ['q' => 'So sánh: 11 - 6 và 6', 'options' => ['>', '<', '=', 'Không so sánh được'], 'answer' => '<'],
                    ['q' => 'Phép tính nào có kết quả là 5?', 'options' => ['11 - 5', '11 - 6', '11 - 7', '11 - 4'], 'answer' => '11 - 6'],
                ]],
                ['topic' => 'Bảng trừ', 'questions' => [
                    ['q' => '14 - 8 = ?', 'options' => ['5', '6', '7', '22'], 'answer' => '6'],
                    ['q' => '16 - 7 = ?', 'options' => ['8', '9', '10', '23'], 'answer' => '9'],
                    ['q' => '12 - 5 = ?', 'options' => ['6', '7', '8', '17'], 'answer' => '7'],
                    ['q' => '15 - 9 = ?', 'options' => ['5', '6', '7', '24'], 'answer' => '6'],
                    ['q' => '13 - 6 = ?', 'options' => ['6', '7', '8', '19'], 'answer' => '7'],
                    ['q' => '17 - 8 = ?', 'options' => ['8', '9', '10', '25'], 'answer' => '9'],
                    ['q' => '18 - 9 = ?', 'options' => ['8', '9', '10', '27'], 'answer' => '9'],
                    ['q' => '12 - 3 = ?', 'options' => ['8', '9', '10', '15'], 'answer' => '9'],
                    ['q' => '14 - 5 = ?', 'options' => ['8', '9', '10', '19'], 'answer' => '9'],
                    ['q' => '13 - 4 = ?', 'options' => ['8', '9', '10', '17'], 'answer' => '9'],
                    ['q' => '15 - 7 = ?', 'options' => ['7', '8', '9', '22'], 'answer' => '8'],
                    ['q' => '12 - 8 = ?', 'options' => ['3', '4', '5', '20'], 'answer' => '4'],
                    ['q' => '16 - 9 = ?', 'options' => ['6', '7', '8', '25'], 'answer' => '7'],
                    ['q' => '13 - 7 = ?', 'options' => ['5', '6', '7', '20'], 'answer' => '6'],
                    ['q' => '14 - 6 = ?', 'options' => ['7', '8', '9', '20'], 'answer' => '8'],
                ]],
                ['topic' => 'Bài toán nhiều hơn, ít hơn', 'questions' => [
                    ['q' => 'An có 15 viên bi, Bình có nhiều hơn An 5 viên. Hỏi Bình có bao nhiêu viên bi?', 'options' => ['10 viên', '20 viên', '25 viên', '5 viên'], 'answer' => '20 viên'],
                    ['q' => 'Cành trên có 12 quả, cành dưới có ít hơn cành trên 4 quả. Hỏi cành dưới có mấy quả?', 'options' => ['8 quả', '16 quả', '10 quả', '4 quả'], 'answer' => '8 quả'],
                    ['q' => 'Để giải bài toán "nhiều hơn", ta thường dùng phép tính gì?', 'options' => ['Cộng', 'Trừ', 'Nhân', 'Chia'], 'answer' => 'Cộng'],
                    ['q' => 'Để giải bài toán "ít hơn", ta thường dùng phép tính gì?', 'options' => ['Cộng', 'Trừ', 'Nhân', 'Chia'], 'answer' => 'Trừ'],
                    ['q' => 'Sợi dây xanh dài 20cm. Sợi dây đỏ dài hơn sợi dây xanh 10cm. Sợi dây đỏ dài?', 'options' => ['10cm', '20cm', '30cm', '40cm'], 'answer' => '30cm'],
                    ['q' => 'Thùng thứ nhất chứa 35 lít dầu. Thùng thứ hai chứa ít hơn thùng thứ nhất 8 lít. Thùng thứ hai chứa?', 'options' => ['27 lít', '43 lít', '30 lít', '8 lít'], 'answer' => '27 lít'],
                    ['q' => 'Bố 35 tuổi, con ít hơn bố 28 tuổi. Hỏi con bao nhiêu tuổi?', 'options' => ['7 tuổi', '8 tuổi', '63 tuổi', '28 tuổi'], 'answer' => '7 tuổi'],
                    ['q' => 'Mẹ cao 160cm, con thấp hơn mẹ 40cm. Hỏi con cao bao nhiêu?', 'options' => ['120cm', '200cm', '140cm', '40cm'], 'answer' => '120cm'],
                    ['q' => 'Câu hỏi "Cả hai có bao nhiêu?" thường là dạng toán gì?', 'options' => ['Nhiều hơn', 'Ít hơn', 'Tìm tổng', 'Tìm hiệu'], 'answer' => 'Tìm tổng'],
                    ['q' => 'Câu hỏi "Hơn bao nhiêu?" thường là dạng toán gì?', 'options' => ['Nhiều hơn', 'Ít hơn', 'Tìm hiệu', 'Tìm tổng'], 'answer' => 'Tìm hiệu'],
                    ['q' => 'Quyển sách dày 100 trang. Quyển vở mỏng hơn quyển sách 52 trang. Quyển vở dày?', 'options' => ['48 trang', '152 trang', '50 trang', '52 trang'], 'answer' => '48 trang'],
                    ['q' => 'Năm nay anh 15 tuổi, em kém anh 6 tuổi. Hỏi năm nay em bao nhiêu tuổi?', 'options' => ['9 tuổi', '21 tuổi', '10 tuổi', '6 tuổi'], 'answer' => '9 tuổi'],
                    ['q' => 'Cây cau cao 8m. Cây dừa cao hơn cây cau 5m. Cây dừa cao?', 'options' => ['3m', '13m', '10m', '5m'], 'answer' => '13m'],
                    ['q' => 'Lớp 2A có 30 học sinh. Lớp 2B có nhiều hơn lớp 2A 2 học sinh. Lớp 2B có?', 'options' => ['28 học sinh', '32 học sinh', '30 học sinh', '62 học sinh'], 'answer' => '32 học sinh'],
                    ['q' => 'Trong bài toán có từ "nhiều hơn", số cần tìm sẽ ... số đã biết?', 'options' => ['Lớn hơn', 'Bé hơn', 'Bằng', 'Gấp đôi'], 'answer' => 'Lớn hơn'],
                ]],
                ['topic' => 'Lít', 'questions' => [
                    ['q' => 'Lít là đơn vị dùng để đo gì?', 'options' => ['Cân nặng', 'Chiều dài', 'Thể tích (Chất lỏng)', 'Nhiệt độ'], 'answer' => 'Thể tích (Chất lỏng)'],
                    ['q' => 'Can dầu 10 lít rót sang can 3 lít. Hỏi trong can to còn lại mấy lít?', 'options' => ['6 lít', '7 lít', '8 lít', '13 lít'], 'answer' => '7 lít'],
                    ['q' => 'Lít được viết tắt là gì?', 'options' => ['l', 'kg', 'm', 'lit'], 'answer' => 'l'],
                    ['q' => 'Vật nào sau đây thường được đo bằng lít?', 'options' => ['Gạo', 'Xăng', 'Sắt', 'Vải'], 'answer' => 'Xăng'],
                    ['q' => 'Can thứ nhất có 15l nước, can thứ hai có 10l. Cả hai can có bao nhiêu lít nước?', 'options' => ['5l', '25l', '30l', '150l'], 'answer' => '25l'],
                    ['q' => 'Thùng nước có 20l, dùng hết một nửa. Trong thùng còn lại bao nhiêu lít?', 'options' => ['5l', '10l', '15l', '20l'], 'answer' => '10l'],
                    ['q' => 'So sánh: 5 lít và 500ml', 'options' => ['5 lít > 500ml', '5 lít < 500ml', '5 lít = 500ml', 'Không so sánh được'], 'answer' => '5 lít > 500ml'],
                    ['q' => 'Một chai nước ngọt có dung tích là 1,5l. Đúng hay Sai?', 'options' => ['Đúng', 'Sai', 'Tùy loại chai', 'Không biết'], 'answer' => 'Đúng'],
                    ['q' => 'Để đo lượng nước trong một cái hồ bơi lớn, người ta có dùng đơn vị lít không?', 'options' => ['Có', 'Không', 'Có thể dùng nhưng không phù hợp', 'Chỉ dùng để đo sữa'], 'answer' => 'Có thể dùng nhưng không phù hợp'],
                    ['q' => 'Thùng sơn có 18 lít, đã dùng hết 1/3 số sơn. Đã dùng hết bao nhiêu lít?', 'options' => ['3 lít', '6 lít', '9 lít', '15 lít'], 'answer' => '6 lít'],
                    ['q' => '1 lít nước tương đương với bao nhiêu kg?', 'options' => ['Khoảng 1kg', 'Khoảng 2kg', 'Không thể biết', '10kg'], 'answer' => 'Khoảng 1kg'],
                    ['q' => '5l + 8l = ?', 'options' => ['12l', '13l', '14l', '3l'], 'answer' => '13l'],
                    ['q' => '20l - 12l = ?', 'options' => ['7l', '8l', '9l', '32l'], 'answer' => '8l'],
                    ['q' => 'Mỗi ngày nhà em dùng hết 2 lít nước để uống. Một tuần nhà em uống hết bao nhiêu lít nước?', 'options' => ['10 lít', '12 lít', '14 lít', '9 lít'], 'answer' => '14 lít'],
                    ['q' => 'Bình nước 20 lít, đã uống hết 5 lít. Hỏi còn lại bao nhiêu lít?', 'options' => ['10 lít', '15 lít', '25 lít', '4 lít'], 'answer' => '15 lít'],
                ]],
                ['topic' => 'Phép cộng có nhớ trong phạm vi 100', 'questions' => [
                    ['q' => '38 + 25 = ?', 'options' => ['53', '63', '73', '513'], 'answer' => '63'],
                    ['q' => '59 + 17 = ?', 'options' => ['66', '76', '86', '75'], 'answer' => '76'],
                    ['q' => '27 + 46 = ?', 'options' => ['63', '73', '83', '613'], 'answer' => '73'],
                    ['q' => '48 + 38 = ?', 'options' => ['76', '86', '96', '716'], 'answer' => '86'],
                    ['q' => 'Khi cộng hàng đơn vị có kết quả là 14, ta viết 4 và nhớ mấy?', 'options' => ['Nhớ 1', 'Nhớ 4', 'Nhớ 10', 'Không nhớ'], 'answer' => 'Nhớ 1'],
                    ['q' => 'Phép cộng có nhớ là phép cộng mà tổng các chữ số ở một hàng ...?', 'options' => ['Bằng 10', 'Lớn hơn 10', 'Lớn hơn hoặc bằng 10', 'Nhỏ hơn 10'], 'answer' => 'Lớn hơn hoặc bằng 10'],
                    ['q' => '19 + 29 = ?', 'options' => ['38', '48', '58', '318'], 'answer' => '48'],
                    ['q' => '65 + 25 = ?', 'options' => ['80', '90', '100', '810'], 'answer' => '90'],
                    ['q' => 'Lớp 2A có 18 bạn nam và 15 bạn nữ. Hỏi lớp 2A có tất cả bao nhiêu bạn?', 'options' => ['23 bạn', '33 bạn', '43 bạn', '3 bạn'], 'answer' => '33 bạn'],
                    ['q' => 'Một cửa hàng buổi sáng bán 45kg gạo, buổi chiều bán 37kg. Cả ngày bán được bao nhiêu kg?', 'options' => ['72kg', '82kg', '92kg', '8kg'], 'answer' => '82kg'],
                    ['q' => 'Số lớn nhất có một chữ số cộng với số lớn nhất có một chữ số là?', 'options' => ['17', '18', '19', '99'], 'answer' => '18'],
                    ['q' => 'Tìm x, biết x - 36 = 27', 'options' => ['9', '53', '63', '513'], 'answer' => '63'],
                    ['q' => 'Tổng của 47 và 23 là?', 'options' => ['60', '70', '80', '610'], 'answer' => '70'],
                    ['q' => 'Phép tính nào có kết quả là 52?', 'options' => ['24 + 27', '25 + 27', '26 + 27', '23 + 28'], 'answer' => '25 + 27'],
                    ['q' => 'Số bé nhất có hai chữ số khác nhau cộng với 15 là?', 'options' => ['25', '26', '27', '24'], 'answer' => '25'],
                ]],
                ['topic' => 'Phép trừ có nhớ trong phạm vi 100', 'questions' => [
                    ['q' => '82 - 47 = ?', 'options' => ['35', '45', '55', '129'], 'answer' => '35'],
                    ['q' => '60 - 28 = ?', 'options' => ['32', '42', '22', '88'], 'answer' => '32'],
                    ['q' => '54 - 19 = ?', 'options' => ['35', '45', '25', '73'], 'answer' => '35'],
                    ['q' => '71 - 33 = ?', 'options' => ['38', '48', '28', '104'], 'answer' => '38'],
                    ['q' => 'Để thực hiện 43 - 18, ở hàng đơn vị ta lấy 13 trừ 8. Đúng hay sai?', 'options' => ['Đúng', 'Sai', 'Tùy trường hợp', 'Không thể trừ'], 'answer' => 'Đúng'],
                    ['q' => 'Phép trừ có nhớ là phép trừ mà ở một hàng, số bị trừ ... số trừ?', 'options' => ['Lớn hơn', 'Bằng', 'Nhỏ hơn', 'Gấp đôi'], 'answer' => 'Nhỏ hơn'],
                    ['q' => '90 - 45 = ?', 'options' => ['45', '55', '35', '135'], 'answer' => '45'],
                    ['q' => '100 - 25 = ?', 'options' => ['65', '75', '85', '125'], 'answer' => '75'],
                    ['q' => 'Sợi dây dài 70cm, cắt đi 25cm. Sợi dây còn lại dài bao nhiêu?', 'options' => ['45cm', '55cm', '95cm', '50cm'], 'answer' => '45cm'],
                    ['q' => 'Mẹ có 52 quả trứng, mẹ đã bán 24 quả. Mẹ còn lại bao nhiêu quả?', 'options' => ['28 quả', '38 quả', '76 quả', '22 quả'], 'answer' => '28 quả'],
                    ['q' => 'Số lớn nhất có hai chữ số trừ đi 19 là?', 'options' => ['70', '80', '90', '118'], 'answer' => '80'],
                    ['q' => 'Tìm x, biết x + 28 = 62', 'options' => ['34', '44', '90', '24'], 'answer' => '34'],
                    ['q' => 'Hiệu của 81 và 39 là?', 'options' => ['42', '52', '120', '32'], 'answer' => '42'],
                    ['q' => 'Phép tính nào có kết quả là 26?', 'options' => ['50 - 24', '60 - 33', '70 - 45', '40 - 15'], 'answer' => '50 - 24'],
                    ['q' => 'Số tròn chục lớn nhất có hai chữ số trừ đi 35 là?', 'options' => ['55', '65', '45', '125'], 'answer' => '55'],
                ]],
                ['topic' => 'Ngày, giờ, tháng', 'questions' => [
                    ['q' => 'Một năm có bao nhiêu tháng?', 'options' => ['10 tháng', '11 tháng', '12 tháng', '13 tháng'], 'answer' => '12 tháng'],
                    ['q' => 'Tháng 9 có bao nhiêu ngày?', 'options' => ['29 ngày', '30 ngày', '31 ngày', '28 ngày'], 'answer' => '30 ngày'],
                    ['q' => 'Một ngày có bao nhiêu giờ?', 'options' => ['12 giờ', '24 giờ', '60 giờ', '48 giờ'], 'answer' => '24 giờ'],
                    ['q' => 'Một giờ có bao nhiêu phút?', 'options' => ['30 phút', '60 phút', '100 phút', '90 phút'], 'answer' => '60 phút'],
                    ['q' => 'Kim ngắn trên đồng hồ chỉ gì?', 'options' => ['Giờ', 'Phút', 'Giây', 'Ngày'], 'answer' => 'Giờ'],
                    ['q' => 'Kim dài trên đồng hồ chỉ gì?', 'options' => ['Giờ', 'Phút', 'Giây', 'Tháng'], 'answer' => 'Phút'],
                    ['q' => 'Tháng 2 của năm không nhuận có bao nhiêu ngày?', 'options' => ['28 ngày', '29 ngày', '30 ngày', '31 ngày'], 'answer' => '28 ngày'],
                    ['q' => 'Những tháng nào có 31 ngày?', 'options' => ['4, 6, 9, 11', '1, 3, 5, 7, 8, 10, 12', 'Chỉ có tháng 1 và 12', 'Tất cả các tháng'], 'answer' => '1, 3, 5, 7, 8, 10, 12'],
                    ['q' => 'Lúc 3 giờ đúng, kim giờ và kim phút tạo thành góc gì?', 'options' => ['Góc vuông', 'Góc nhọn', 'Góc tù', 'Góc bẹt'], 'answer' => 'Góc vuông'],
                    ['q' => 'Ngày Quốc khánh nước ta là ngày nào?', 'options' => ['30/4', '1/5', '2/9', '1/1'], 'answer' => '2/9'],
                    ['q' => 'Một quý có mấy tháng?', 'options' => ['2 tháng', '3 tháng', '4 tháng', '6 tháng'], 'answer' => '3 tháng'],
                    ['q' => 'Năm nhuận là năm mà tháng 2 có bao nhiêu ngày?', 'options' => ['28 ngày', '29 ngày', '30 ngày', '27 ngày'], 'answer' => '29 ngày'],
                    ['q' => 'Bây giờ là 8 giờ sáng, 3 tiếng nữa là mấy giờ?', 'options' => ['10 giờ', '11 giờ', '12 giờ trưa', '5 giờ'], 'answer' => '11 giờ'],
                    ['q' => 'Một bộ phim dài 90 phút. Tức là dài bao nhiêu giờ?', 'options' => ['1 giờ', '1 giờ rưỡi', '2 giờ', '3 giờ'], 'answer' => '1 giờ rưỡi'],
                    ['q' => 'Lúc 6 giờ 30 phút, kim dài chỉ số mấy?', 'options' => ['Số 12', 'Số 3', 'Số 6', 'Số 9'], 'answer' => 'Số 6'],
                ]],
            ],
            // ========== LỚP 3 ==========
            3 => [
                ['topic' => 'Ôn tập cộng, trừ trong phạm vi 1 000', 'questions' => [
                    ['q' => '350 + 250 = ?', 'options' => ['500', '600', '700', '550'], 'answer' => '600'],
                    ['q' => '800 - 120 = ?', 'options' => ['680', '780', '720', '920'], 'answer' => '680'],
                    ['q' => 'Số liền sau của 999 là?', 'options' => ['998', '1000', '1001', '990'], 'answer' => '1000'],
                    ['q' => '456 + 231 = ?', 'options' => ['687', '677', '686', '225'], 'answer' => '687'],
                    ['q' => '987 - 765 = ?', 'options' => ['222', '232', '322', '1752'], 'answer' => '222'],
                    ['q' => 'Số lớn nhất có ba chữ số là?', 'options' => ['900', '990', '999', '1000'], 'answer' => '999'],
                    ['q' => 'Tổng của 500 và 350 là?', 'options' => ['800', '850', '900', '150'], 'answer' => '850'],
                    ['q' => 'Hiệu của 1000 và 250 là?', 'options' => ['750', '850', '800', '1250'], 'answer' => '750'],
                    ['q' => 'Trang trại có 450 con gà, đã bán đi 150 con. Hỏi còn lại bao nhiêu con?', 'options' => ['250 con', '300 con', '350 con', '600 con'], 'answer' => '300 con'],
                    ['q' => 'Tìm x, biết x + 200 = 600', 'options' => ['300', '400', '800', '500'], 'answer' => '400'],
                    ['q' => 'Tìm y, biết 750 - y = 300', 'options' => ['450', '550', '1050', '400'], 'answer' => '450'],
                    ['q' => '123 + 456 + 200 = ?', 'options' => ['779', '769', '789', '879'], 'answer' => '779'],
                    ['q' => 'Số bé nhất có ba chữ số khác nhau là?', 'options' => ['100', '102', '123', '101'], 'answer' => '102'],
                    ['q' => 'Tổng của số lớn nhất và số bé nhất có 3 chữ số là?', 'options' => ['1099', '1000', '1100', '1098'], 'answer' => '1099'],
                    ['q' => 'Một cửa hàng có 860kg gạo, đã bán 340kg. Cửa hàng còn lại?', 'options' => ['520kg', '530kg', '540kg', '1200kg'], 'answer' => '520kg'],
                ]],
                ['topic' => 'Bảng nhân 6, bảng chia 6', 'questions' => [
                    ['q' => '6 x 8 = ?', 'options' => ['42', '48', '54', '14'], 'answer' => '48'],
                    ['q' => '42 : 6 = ?', 'options' => ['6', '7', '8', '36'], 'answer' => '7'],
                    ['q' => '6 x 7 = ?', 'options' => ['36', '42', '48', '13'], 'answer' => '42'],
                    ['q' => '54 : 6 = ?', 'options' => ['8', '9', '10', '48'], 'answer' => '9'],
                    ['q' => 'Thừa số thứ nhất là 6, thừa số thứ hai là 5. Tích là?', 'options' => ['11', '30', '1', '25'], 'answer' => '30'],
                    ['q' => 'Số bị chia là 24, số chia là 6. Thương là?', 'options' => ['4', '18', '30', '144'], 'answer' => '4'],
                    ['q' => 'Mỗi hộp có 6 cái bút. 7 hộp như vậy có bao nhiêu cái bút?', 'options' => ['13 bút', '42 bút', '48 bút', '1 bút'], 'answer' => '42 bút'],
                    ['q' => 'Có 36 học sinh xếp thành 6 hàng đều nhau. Mỗi hàng có mấy học sinh?', 'options' => ['5 học sinh', '6 học sinh', '7 học sinh', '30 học sinh'], 'answer' => '6 học sinh'],
                    ['q' => 'Tìm x, biết x : 6 = 8', 'options' => ['14', '2', '48', '40'], 'answer' => '48'],
                    ['q' => 'Tìm y, biết y * 6 = 60', 'options' => ['10', '54', '66', '6'], 'answer' => '10'],
                    ['q' => 'Phép tính nào có kết quả bằng 18?', 'options' => ['6 x 2', '6 x 3', '6 x 4', '12 + 6'], 'answer' => '6 x 3'],
                    ['q' => 'Phép tính nào có kết quả bằng 5?', 'options' => ['11 : 6', '24 : 6', '30 : 6', '30 - 25'], 'answer' => '30 : 6'],
                    ['q' => 'Trong phép nhân 6 x 9 = 54, số 6 và 9 được gọi là?', 'options' => ['Thừa số', 'Tích', 'Thương', 'Tổng'], 'answer' => 'Thừa số'],
                    ['q' => 'Trong phép chia 48 : 6 = 8, số 8 được gọi là?', 'options' => ['Số chia', 'Số bị chia', 'Thương', 'Hiệu'], 'answer' => 'Thương'],
                    ['q' => 'Gấp 6 lên 9 lần được?', 'options' => ['15', '54', '3', '69'], 'answer' => '54'],
                ]],
                ['topic' => 'Bảng nhân 7, bảng chia 7', 'questions' => [
                    ['q' => '7 x 9 = ?', 'options' => ['56', '63', '70', '16'], 'answer' => '63'],
                    ['q' => '49 : 7 = ?', 'options' => ['6', '7', '8', '42'], 'answer' => '7'],
                    ['q' => '7 x 5 = ?', 'options' => ['35', '42', '49', '12'], 'answer' => '35'],
                    ['q' => '21 : 7 = ?', 'options' => ['3', '4', '5', '14'], 'answer' => '3'],
                    ['q' => 'Một tuần có 7 ngày. 5 tuần có bao nhiêu ngày?', 'options' => ['12 ngày', '30 ngày', '35 ngày', '2 ngày'], 'answer' => '35 ngày'],
                    ['q' => 'Có 56 viên bi chia đều cho 7 bạn. Mỗi bạn được mấy viên?', 'options' => ['7 viên', '8 viên', '9 viên', '49 viên'], 'answer' => '8 viên'],
                    ['q' => 'Kết quả của phép nhân 7 x 8 là?', 'options' => ['54', '56', '64', '15'], 'answer' => '56'],
                    ['q' => 'Kết quả của phép chia 70 : 7 là?', 'options' => ['1', '10', '7', '63'], 'answer' => '10'],
                    ['q' => 'Tìm x, biết 42 : x = 7', 'options' => ['6', '7', '8', '35'], 'answer' => '6'],
                    ['q' => 'Tìm y, biết y x 7 = 28', 'options' => ['3', '4', '5', '21'], 'answer' => '4'],
                    ['q' => 'Phép tính nào có tích bằng 14?', 'options' => ['7 x 1', '7 x 2', '7 x 3', '21 - 7'], 'answer' => '7 x 2'],
                    ['q' => 'Thương của 35 và 7 là?', 'options' => ['4', '5', '6', '28'], 'answer' => '5'],
                    ['q' => 'Số nào trong dãy số sau thuộc bảng nhân 7? 15, 21, 25', 'options' => ['15', '21', '25', '14'], 'answer' => '21'],
                    ['q' => 'Số nào trong dãy số sau chia hết cho 7? 20, 28, 30', 'options' => ['20', '28', '30', '7'], 'answer' => '28'],
                    ['q' => 'Gấp 7 lên 6 lần được?', 'options' => ['13', '42', '1', '49'], 'answer' => '42'],
                ]],
                ['topic' => 'Bảng nhân 8, bảng chia 8', 'questions' => [
                    ['q' => '8 x 5 = ?', 'options' => ['40', '48', '56', '13'], 'answer' => '40'],
                    ['q' => '64 : 8 = ?', 'options' => ['7', '8', '9', '56'], 'answer' => '8'],
                    ['q' => '8 x 9 = ?', 'options' => ['64', '72', '80', '17'], 'answer' => '72'],
                    ['q' => '32 : 8 = ?', 'options' => ['3', '4', '5', '24'], 'answer' => '4'],
                    ['q' => 'Mỗi con nhện có 8 chân. 6 con nhện có bao nhiêu chân?', 'options' => ['14 chân', '42 chân', '48 chân', '2 chân'], 'answer' => '48 chân'],
                    ['q' => 'Có 40 học sinh, xếp thành các hàng, mỗi hàng 8 em. Xếp được mấy hàng?', 'options' => ['5 hàng', '6 hàng', '7 hàng', '32 hàng'], 'answer' => '5 hàng'],
                    ['q' => 'Tích của 8 và 7 là?', 'options' => ['15', '56', '1', '64'], 'answer' => '56'],
                    ['q' => 'Thương của 80 và 8 là?', 'options' => ['10', '72', '88', '8'], 'answer' => '10'],
                    ['q' => 'Tìm x, biết x * 8 = 24', 'options' => ['3', '4', '5', '16'], 'answer' => '3'],
                    ['q' => 'Tìm y, biết 16 : y = 8', 'options' => ['1', '2', '3', '8'], 'answer' => '2'],
                    ['q' => 'Phép tính nào có kết quả là 40?', 'options' => ['8 x 4', '8 x 5', '8 x 6', '48 - 8'], 'answer' => '8 x 5'],
                    ['q' => 'Số nào chia cho 8 được 9?', 'options' => ['63', '72', '81', '17'], 'answer' => '72'],
                    ['q' => 'Gấp 8 lên 8 lần được?', 'options' => ['16', '64', '1', '88'], 'answer' => '64'],
                    ['q' => 'Giảm 48 đi 8 lần được?', 'options' => ['6', '40', '56', '8'], 'answer' => '6'],
                    ['q' => '8 x 10 = ?', 'options' => ['18', '8', '80', '10'], 'answer' => '80'],
                ]],
                ['topic' => 'Bảng nhân 9, bảng chia 9', 'questions' => [
                    ['q' => '9 x 9 = ?', 'options' => ['72', '81', '90', '18'], 'answer' => '81'],
                    ['q' => '54 : 9 = ?', 'options' => ['5', '6', '7', '45'], 'answer' => '6'],
                    ['q' => '9 x 7 = ?', 'options' => ['56', '63', '72', '16'], 'answer' => '63'],
                    ['q' => '27 : 9 = ?', 'options' => ['3', '4', '5', '18'], 'answer' => '3'],
                    ['q' => 'Một hộp bánh có 9 cái. 8 hộp có bao nhiêu cái bánh?', 'options' => ['17 cái', '72 cái', '81 cái', '1 cái'], 'answer' => '72 cái'],
                    ['q' => 'Chia đều 45 quyển vở cho 9 học sinh. Mỗi học sinh được mấy quyển?', 'options' => ['4 quyển', '5 quyển', '6 quyển', '36 quyển'], 'answer' => '5 quyển'],
                    ['q' => 'Tích của 9 và 6 là?', 'options' => ['54', '63', '15', '3'], 'answer' => '54'],
                    ['q' => 'Thương của 90 và 9 là?', 'options' => ['10', '81', '99', '9'], 'answer' => '10'],
                    ['q' => 'Tìm x, biết 9 * x = 36', 'options' => ['3', '4', '5', '27'], 'answer' => '4'],
                    ['q' => 'Tìm y, biết y : 9 = 2', 'options' => ['11', '7', '18', '4.5'], 'answer' => '18'],
                    ['q' => 'Phép tính nào có kết quả là 63?', 'options' => ['9 x 6', '9 x 7', '9 x 8', '72 - 9'], 'answer' => '9 x 7'],
                    ['q' => 'Số nào chia cho 9 được 8?', 'options' => ['64', '72', '80', '17'], 'answer' => '72'],
                    ['q' => 'Gấp 9 lên 5 lần được?', 'options' => ['14', '45', '4', '95'], 'answer' => '45'],
                    ['q' => 'Giảm 81 đi 9 lần được?', 'options' => ['9', '72', '90', '819'], 'answer' => '9'],
                    ['q' => 'Tổng các chữ số của một số chia hết cho 9 thì?', 'options' => ['Chia hết cho 9', 'Không chia hết cho 9', 'Chia hết cho 3', 'Là số lẻ'], 'answer' => 'Chia hết cho 9'],
                ]],
                ['topic' => 'Tìm thành phần phép nhân, phép chia', 'questions' => [
                    ['q' => 'Tìm x, biết x * 5 = 45', 'options' => ['8', '9', '10', '40'], 'answer' => '9'],
                    ['q' => 'Tìm y, biết 56 : y = 8', 'options' => ['6', '7', '8', '64'], 'answer' => '7'],
                    ['q' => 'Muốn tìm thừa số chưa biết, ta làm thế nào?', 'options' => ['Lấy tích chia cho thừa số đã biết', 'Lấy tích nhân với thừa số đã biết', 'Lấy thừa số đã biết chia cho tích', 'Lấy tích cộng thừa số đã biết'], 'answer' => 'Lấy tích chia cho thừa số đã biết'],
                    ['q' => 'Muốn tìm số chia, ta làm thế nào?', 'options' => ['Lấy số bị chia chia cho thương', 'Lấy thương nhân với số bị chia', 'Lấy số bị chia nhân với thương', 'Lấy thương cộng số bị chia'], 'answer' => 'Lấy số bị chia chia cho thương'],
                    ['q' => 'Muốn tìm số bị chia, ta làm thế nào?', 'options' => ['Lấy thương nhân với số chia', 'Lấy thương chia cho số chia', 'Lấy số chia chia cho thương', 'Lấy số chia trừ thương'], 'answer' => 'Lấy thương nhân với số chia'],
                    ['q' => 'Tìm x, biết x : 7 = 6', 'options' => ['13', '1', '42', '49'], 'answer' => '42'],
                    ['q' => 'Tìm y, biết 8 * y = 48', 'options' => ['6', '40', '56', '8'], 'answer' => '6'],
                    ['q' => 'Tìm z, biết 63 : z = 9', 'options' => ['7', '54', '72', '9'], 'answer' => '7'],
                    ['q' => 'Một số nhân với 4 được 36. Số đó là?', 'options' => ['8', '9', '10', '32'], 'answer' => '9'],
                    ['q' => 'Một số chia cho 5 được 10. Số đó là?', 'options' => ['2', '15', '50', '5'], 'answer' => '50'],
                    ['q' => 'Trong phép nhân, kết quả được gọi là?', 'options' => ['Thương', 'Tổng', 'Tích', 'Hiệu'], 'answer' => 'Tích'],
                    ['q' => 'Trong phép chia, số bị đem đi chia gọi là?', 'options' => ['Số chia', 'Số bị chia', 'Thương', 'Số hạng'], 'answer' => 'Số bị chia'],
                    ['q' => 'x * 10 = 100. x = ?', 'options' => ['1', '10', '1000', '90'], 'answer' => '10'],
                    ['q' => 'x : 1 = 25. x = ?', 'options' => ['1', '24', '25', '26'], 'answer' => '25'],
                    ['q' => '40 : x = 4. x = ?', 'options' => ['10', '36', '44', '160'], 'answer' => '10'],
                ]],
                ['topic' => 'Một phần mấy', 'questions' => [
                    ['q' => '1/4 của 20 là bao nhiêu?', 'options' => ['4', '5', '6', '16'], 'answer' => '5'],
                    ['q' => 'Lớp 3A có 30 bạn, 1/3 trong số đó là học sinh giỏi. Hỏi lớp có bao nhiêu học sinh giỏi?', 'options' => ['9 bạn', '10 bạn', '11 bạn', '27 bạn'], 'answer' => '10 bạn'],
                    ['q' => 'Để tìm 1/5 của một số, ta lấy số đó làm gì?', 'options' => ['Nhân với 5', 'Chia cho 5', 'Cộng với 5', 'Trừ 5'], 'answer' => 'Chia cho 5'],
                    ['q' => '1/2 của 18 là?', 'options' => ['8', '9', '10', '36'], 'answer' => '9'],
                    ['q' => '1/6 của 42 là?', 'options' => ['6', '7', '8', '36'], 'answer' => '7'],
                    ['q' => 'Mẹ có 24 cái kẹo, mẹ cho An 1/4 số kẹo. Mẹ cho An mấy cái?', 'options' => ['4 cái', '6 cái', '8 cái', '20 cái'], 'answer' => '6 cái'],
                    ['q' => 'Sợi dây dài 35m, cắt đi 1/7 sợi dây. Đã cắt đi bao nhiêu mét?', 'options' => ['5m', '6m', '7m', '28m'], 'answer' => '5m'],
                    ['q' => 'Một giờ có 60 phút. 1/6 của một giờ là bao nhiêu phút?', 'options' => ['6 phút', '10 phút', '12 phút', '54 phút'], 'answer' => '10 phút'],
                    ['q' => 'Số nào có 1/8 bằng 5?', 'options' => ['13', '3', '40', '5/8'], 'answer' => '40'],
                    ['q' => 'Đã tô màu 1/3 của hình nào?', 'options' => ['Hình có 3 phần, tô 1 phần', 'Hình có 3 phần, tô 2 phần', 'Hình có 2 phần, tô 1 phần', 'Hình có 4 phần, tô 1 phần'], 'answer' => 'Hình có 3 phần, tô 1 phần'],
                    ['q' => 'So sánh 1/2 và 1/3', 'options' => ['1/2 > 1/3', '1/2 < 1/3', '1/2 = 1/3', 'Không so sánh được'], 'answer' => '1/2 > 1/3'],
                    ['q' => 'So sánh 1/5 và 1/8', 'options' => ['1/5 > 1/8', '1/5 < 1/8', '1/5 = 1/8', 'Không so sánh được'], 'answer' => '1/5 > 1/8'],
                    ['q' => 'Tìm 1/9 của 81', 'options' => ['8', '9', '10', '72'], 'answer' => '9'],
                    ['q' => 'Một đàn gà có 40 con, trong đó 1/5 là gà trống. Hỏi có bao nhiêu gà mái?', 'options' => ['8 con', '32 con', '35 con', '45 con'], 'answer' => '32 con'],
                    ['q' => '1/7 của 49 là?', 'options' => ['6', '7', '8', '42'], 'answer' => '7'],
                ]],
                ['topic' => 'Góc, góc vuông, góc không vuông', 'questions' => [
                    ['q' => 'Góc lớn hơn góc vuông được gọi là?', 'options' => ['Góc nhọn', 'Góc tù', 'Góc bẹt', 'Góc thẳng'], 'answer' => 'Góc tù'],
                    ['q' => 'Dùng dụng cụ nào để kiểm tra góc vuông?', 'options' => ['Com-pa', 'Thước kẻ', 'Ê-ke', 'Thước đo độ'], 'answer' => 'Ê-ke'],
                    ['q' => 'Góc bé hơn góc vuông được gọi là?', 'options' => ['Góc nhọn', 'Góc tù', 'Góc bẹt', 'Góc tròn'], 'answer' => 'Góc nhọn'],
                    ['q' => 'Lúc 3 giờ đúng, kim giờ và kim phút của đồng hồ tạo thành góc gì?', 'options' => ['Góc nhọn', 'Góc vuông', 'Góc tù', 'Góc bẹt'], 'answer' => 'Góc vuông'],
                    ['q' => 'Hình chữ nhật có mấy góc vuông?', 'options' => ['2', '3', '4', '1'], 'answer' => '4'],
                    ['q' => 'Hình tam giác vuông có mấy góc vuông?', 'options' => ['1', '2', '3', '0'], 'answer' => '1'],
                    ['q' => 'Góc tạo bởi hai cạnh kề của một hình vuông là góc gì?', 'options' => ['Góc nhọn', 'Góc vuông', 'Góc tù', 'Góc bẹt'], 'answer' => 'Góc vuông'],
                    ['q' => 'Lúc 1 giờ đúng, kim giờ và kim phút tạo thành góc gì?', 'options' => ['Góc nhọn', 'Góc vuông', 'Góc tù', 'Góc bẹt'], 'answer' => 'Góc nhọn'],
                    ['q' => 'Lúc 5 giờ đúng, kim giờ và kim phút tạo thành góc gì?', 'options' => ['Góc nhọn', 'Góc vuông', 'Góc tù', 'Góc bẹt'], 'answer' => 'Góc tù'],
                    ['q' => 'Góc có số đo 90 độ là góc gì?', 'options' => ['Góc nhọn', 'Góc vuông', 'Góc tù', 'Góc bẹt'], 'answer' => 'Góc vuông'],
                    ['q' => 'Góc có số đo 60 độ là góc gì?', 'options' => ['Góc nhọn', 'Góc vuông', 'Góc tù', 'Góc bẹt'], 'answer' => 'Góc nhọn'],
                    ['q' => 'Góc có số đo 120 độ là góc gì?', 'options' => ['Góc nhọn', 'Góc vuông', 'Góc tù', 'Góc bẹt'], 'answer' => 'Góc tù'],
                    ['q' => 'Góc được tạo bởi hai tia chung gốc được gọi là gì?', 'options' => ['Đỉnh', 'Cạnh', 'Góc', 'Đoạn thẳng'], 'answer' => 'Góc'],
                    ['q' => 'Trong một tam giác, có thể có 2 góc tù không?', 'options' => ['Có', 'Không', 'Chỉ tam giác đều', 'Chỉ tam giác cân'], 'answer' => 'Không'],
                    ['q' => 'Góc bẹt bằng mấy lần góc vuông?', 'options' => ['1 lần', '2 lần', '3 lần', '4 lần'], 'answer' => '2 lần'],
                ]],
                 ['topic' => 'Hình chữ nhật, hình vuông', 'questions' => [
                    ['q' => 'Chu vi hình vuông có cạnh 6cm là?', 'options' => ['24 cm', '36 cm', '12 cm', '6 cm'], 'answer' => '24 cm'],
                    ['q' => 'Diện tích hình chữ nhật có chiều dài 8m, rộng 5m là?', 'options' => ['26 m2', '13 m2', '40 m2', '85 m2'], 'answer' => '40 m2'],
                    ['q' => 'Hình vuông có đặc điểm gì?', 'options' => ['4 cạnh bằng nhau, 4 góc vuông', '2 cặp cạnh đối bằng nhau', 'Chỉ có 2 góc vuông', 'Các cạnh không bằng nhau'], 'answer' => '4 cạnh bằng nhau, 4 góc vuông'],
                    ['q' => 'Công thức tính chu vi hình chữ nhật là?', 'options' => ['(dài + rộng) x 2', 'dài x rộng', 'cạnh x 4', 'dài + rộng'], 'answer' => '(dài + rộng) x 2'],
                    ['q' => 'Công thức tính diện tích hình vuông là?', 'options' => ['cạnh + cạnh', 'cạnh x 2', 'cạnh x cạnh', 'cạnh x 4'], 'answer' => 'cạnh x cạnh'],
                    ['q' => 'Chu vi hình chữ nhật có chiều dài 10cm, rộng 5cm là?', 'options' => ['15cm', '30cm', '50cm', '25cm'], 'answer' => '30cm'],
                    ['q' => 'Diện tích hình vuông có cạnh 5dm là?', 'options' => ['20 dm2', '25 dm2', '50 dm2', '10 dm2'], 'answer' => '25 dm2'],
                    ['q' => 'Một hình chữ nhật có chu vi 20m, chiều dài 6m. Chiều rộng là?', 'options' => ['4m', '8m', '14m', '10m'], 'answer' => '4m'],
                    ['q' => 'Một hình vuông có diện tích 36 cm2. Cạnh của hình vuông là?', 'options' => ['6cm', '9cm', '18cm', '4cm'], 'answer' => '6cm'],
                    ['q' => 'Hình vuông có phải là một trường hợp đặc biệt của hình chữ nhật không?', 'options' => ['Có', 'Không', 'Tùy trường hợp', 'Không liên quan'], 'answer' => 'Có'],
                    ['q' => 'Để lát nền một căn phòng hình chữ nhật, ta cần tính gì của căn phòng?', 'options' => ['Chu vi', 'Diện tích', 'Chiều dài', 'Chiều rộng'], 'answer' => 'Diện tích'],
                    ['q' => 'Để làm hàng rào xung quanh một khu vườn hình vuông, ta cần tính gì?', 'options' => ['Chu vi', 'Diện tích', 'Cạnh', 'Góc'], 'answer' => 'Chu vi'],
                    ['q' => 'Chu vi hình vuông có cạnh 10m là?', 'options' => ['20m', '40m', '100m', '30m'], 'answer' => '40m'],
                    ['q' => 'Diện tích hình chữ nhật có chiều dài 12cm, rộng 5cm là?', 'options' => ['17cm2', '34cm2', '60cm2', '24cm2'], 'answer' => '60cm2'],
                    ['q' => 'Một sân chơi hình chữ nhật có diện tích 150m2, chiều rộng 10m. Chiều dài là?', 'options' => ['15m', '25m', '140m', '160m'], 'answer' => '15m'],
                ]],
                 ['topic' => 'Nhân số có hai chữ số với số có một chữ số', 'questions' => [
                    ['q' => '24 x 2 = ?', 'options' => ['46', '48', '50', '26'], 'answer' => '48'],
                    ['q' => '31 x 3 = ?', 'options' => ['93', '63', '34', '94'], 'answer' => '93'],
                    ['q' => '15 x 4 = ?', 'options' => ['40', '50', '60', '19'], 'answer' => '60'],
                    ['q' => '37 x 2 = ?', 'options' => ['64', '74', '84', '39'], 'answer' => '74'],
                    ['q' => 'Mỗi lớp có 25 học sinh. Hỏi 3 lớp như vậy có bao nhiêu học sinh?', 'options' => ['65', '75', '85', '28'], 'answer' => '75'],
                    ['q' => '12 x 8 = ?', 'options' => ['86', '96', '106', '20'], 'answer' => '96'],
                    ['q' => 'Tìm x, biết x : 5 = 15', 'options' => ['3', '20', '75', '50'], 'answer' => '75'],
                    ['q' => 'Kết quả của phép nhân được gọi là gì?', 'options' => ['Tổng', 'Hiệu', 'Tích', 'Thương'], 'answer' => 'Tích'],
                    ['q' => '20 x 4 = ?', 'options' => ['24', '60', '80', '8'], 'answer' => '80'],
                    ['q' => 'Gấp 18 lên 3 lần được?', 'options' => ['21', '44', '54', '48'], 'answer' => '54'],
                    ['q' => 'Một xe ô tô chở 12 người. Hỏi 5 xe như vậy chở bao nhiêu người?', 'options' => ['17', '60', '50', '48'], 'answer' => '60'],
                    ['q' => '45 x 2 = ?', 'options' => ['80', '90', '100', '47'], 'answer' => '90'],
                    ['q' => 'Khi nhân một số với 1, kết quả là?', 'options' => ['1', '0', 'Chính nó', '10'], 'answer' => 'Chính nó'],
                    ['q' => 'Khi nhân một số với 0, kết quả là?', 'options' => ['1', '0', 'Chính nó', 'Không tính được'], 'answer' => '0'],
                    ['q' => '33 x 3 = ?', 'options' => ['36', '66', '99', '93'], 'answer' => '99'],
                ]],
                 ['topic' => 'Phép chia hết, phép chia có dư', 'questions' => [
                    ['q' => '15 : 3 = 5. Đây là phép chia gì?', 'options' => ['Phép chia hết', 'Phép chia có dư', 'Phép cộng', 'Phép nhân'], 'answer' => 'Phép chia hết'],
                    ['q' => '17 : 3 = ?', 'options' => ['5 (dư 1)', '5 (dư 2)', '6 (dư -1)', '6 (dư 1)'], 'answer' => '5 (dư 2)'],
                    ['q' => 'Trong phép chia có dư, số dư phải như thế nào so với số chia?', 'options' => ['Lớn hơn', 'Bằng', 'Nhỏ hơn', 'Lớn hơn hoặc bằng'], 'answer' => 'Nhỏ hơn'],
                    ['q' => 'Phép chia nào sau đây có số dư là 3?', 'options' => ['23 : 4', '24 : 5', '25 : 6', '20 : 3'], 'answer' => '23 : 4'],
                    ['q' => 'Có 20 quả táo chia đều cho 6 bạn. Mỗi bạn được mấy quả và còn dư mấy quả?', 'options' => ['3 quả, dư 2 quả', '2 quả, dư 8 quả', '4 quả, dư 0 quả', '3 quả, dư 0 quả'], 'answer' => '3 quả, dư 2 quả'],
                    ['q' => 'Số nào sau đây chia hết cho 5?', 'options' => ['12', '23', '35', '41'], 'answer' => '35'],
                    ['q' => 'Số nào sau đây chia cho 2 có dư?', 'options' => ['10', '14', '18', '21'], 'answer' => '21'],
                    ['q' => '30 : 5 = ?', 'options' => ['5', '6', '7', '8'], 'answer' => '6'],
                    ['q' => '25 : 4 có số dư là bao nhiêu?', 'options' => ['0', '1', '2', '3'], 'answer' => '1'],
                    ['q' => 'Một số chia cho 7 được thương là 5 và dư 3. Số đó là?', 'options' => ['38', '32', '15', '53'], 'answer' => '38'],
                    ['q' => 'Trong phép chia hết, số dư bằng bao nhiêu?', 'options' => ['1', '0', 'Bằng số chia', 'Bằng số bị chia'], 'answer' => '0'],
                    ['q' => 'Số lớn nhất có 1 chữ số chia cho 3 có số dư là?', 'options' => ['0', '1', '2', '3'], 'answer' => '0'],
                    ['q' => 'Số bé nhất có hai chữ số chia cho 4 có số dư là?', 'options' => ['0', '1', '2', '3'], 'answer' => '2'],
                    ['q' => 'Có 32 học sinh, mỗi bàn ngồi được 5 học sinh. Cần ít nhất bao nhiêu bàn?', 'options' => ['5 bàn', '6 bàn', '7 bàn', '8 bàn'], 'answer' => '7 bàn'],
                    ['q' => 'Một năm có 365 ngày. Một tuần có 7 ngày. Hỏi 365 ngày có bao nhiêu tuần và dư mấy ngày?', 'options' => ['52 tuần, dư 1 ngày', '52 tuần, dư 0 ngày', '51 tuần, dư 8 ngày', '53 tuần, dư -1 ngày'], 'answer' => '52 tuần, dư 1 ngày'],
                ]],
            ]
        ];
    }
}

